// <auto-generated/>
#pragma warning disable CS0618
using DoclingServe.V1.Clear.Converters;
using DoclingServe.V1.Clear.Results;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DoclingServe.V1.Clear
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\clear
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ClearRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The converters property</summary>
        public global::DoclingServe.V1.Clear.Converters.ConvertersRequestBuilder Converters
        {
            get => new global::DoclingServe.V1.Clear.Converters.ConvertersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The results property</summary>
        public global::DoclingServe.V1.Clear.Results.ResultsRequestBuilder Results
        {
            get => new global::DoclingServe.V1.Clear.Results.ResultsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.V1.Clear.ClearRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClearRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/clear", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.V1.Clear.ClearRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClearRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/clear", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
