// <auto-generated/>
#pragma warning disable CS0618
using DoclingServe.Health;
using DoclingServe.Openapi30Json;
using DoclingServe.V1;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DoclingServe
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DoclingServe : BaseRequestBuilder
    {
        /// <summary>The health property</summary>
        public global::DoclingServe.Health.HealthRequestBuilder Health
        {
            get => new global::DoclingServe.Health.HealthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The openapi30Json property</summary>
        public global::DoclingServe.Openapi30Json.Openapi30JsonRequestBuilder Openapi30Json
        {
            get => new global::DoclingServe.Openapi30Json.Openapi30JsonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The v1 property</summary>
        public global::DoclingServe.V1.V1RequestBuilder V1
        {
            get => new global::DoclingServe.V1.V1RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.DoclingServe"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DoclingServe(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
