// <auto-generated/>
#pragma warning disable CS0618
using DoclingServe.V1.Chunk;
using DoclingServe.V1.Clear;
using DoclingServe.V1.ConvertNamespace;
using DoclingServe.V1.Result;
using DoclingServe.V1.Status;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DoclingServe.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The chunk property</summary>
        public global::DoclingServe.V1.Chunk.ChunkRequestBuilder Chunk
        {
            get => new global::DoclingServe.V1.Chunk.ChunkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The clear property</summary>
        public global::DoclingServe.V1.Clear.ClearRequestBuilder Clear
        {
            get => new global::DoclingServe.V1.Clear.ClearRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The convert property</summary>
        public global::DoclingServe.V1.ConvertNamespace.ConvertRequestBuilder Convert
        {
            get => new global::DoclingServe.V1.ConvertNamespace.ConvertRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The result property</summary>
        public global::DoclingServe.V1.Result.ResultRequestBuilder Result
        {
            get => new global::DoclingServe.V1.Result.ResultRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::DoclingServe.V1.Status.StatusRequestBuilder Status
        {
            get => new global::DoclingServe.V1.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
