// <auto-generated/>
#pragma warning disable CS0618
using DoclingServe.V1.Chunk.Hierarchical;
using DoclingServe.V1.Chunk.Hybrid;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DoclingServe.V1.Chunk
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\chunk
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChunkRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The hierarchical property</summary>
        public global::DoclingServe.V1.Chunk.Hierarchical.HierarchicalRequestBuilder Hierarchical
        {
            get => new global::DoclingServe.V1.Chunk.Hierarchical.HierarchicalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The hybrid property</summary>
        public global::DoclingServe.V1.Chunk.Hybrid.HybridRequestBuilder Hybrid
        {
            get => new global::DoclingServe.V1.Chunk.Hybrid.HybridRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.V1.Chunk.ChunkRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChunkRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/chunk", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.V1.Chunk.ChunkRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChunkRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/chunk", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
