// <auto-generated/>
#pragma warning disable CS0618
using DoclingServe.V1.Status.Poll;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DoclingServe.V1.Status
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\status
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StatusRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The poll property</summary>
        public global::DoclingServe.V1.Status.Poll.PollRequestBuilder Poll
        {
            get => new global::DoclingServe.V1.Status.Poll.PollRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.V1.Status.StatusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatusRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/status", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.V1.Status.StatusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatusRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/status", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
