// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DoclingServe.Models
{
    /// <summary>
    /// BoundingBox.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BoundingBox : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The b property</summary>
        public double? B { get; set; }
        /// <summary>CoordOrigin.</summary>
        public global::DoclingServe.Models.CoordOrigin? CoordOrigin { get; set; }
        /// <summary>The l property</summary>
        public double? L { get; set; }
        /// <summary>The r property</summary>
        public double? R { get; set; }
        /// <summary>The t property</summary>
        public double? T { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.Models.BoundingBox"/> and sets the default values.
        /// </summary>
        public BoundingBox()
        {
            AdditionalData = new Dictionary<string, object>();
            CoordOrigin = global::DoclingServe.Models.CoordOrigin.TOPLEFT;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DoclingServe.Models.BoundingBox"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DoclingServe.Models.BoundingBox CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DoclingServe.Models.BoundingBox();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "b", n => { B = n.GetDoubleValue(); } },
                { "coord_origin", n => { CoordOrigin = n.GetEnumValue<global::DoclingServe.Models.CoordOrigin>(); } },
                { "l", n => { L = n.GetDoubleValue(); } },
                { "r", n => { R = n.GetDoubleValue(); } },
                { "t", n => { T = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("b", B);
            writer.WriteEnumValue<global::DoclingServe.Models.CoordOrigin>("coord_origin", CoordOrigin);
            writer.WriteDoubleValue("l", L);
            writer.WriteDoubleValue("r", R);
            writer.WriteDoubleValue("t", T);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
