// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DoclingServe.Models
{
    /// <summary>
    /// A single chunk of a document with its metadata and content.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChunkedDocumentResultItem : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>List of captions for this chunk (e.g. for pictures and tables)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_captions? Captions { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_captions Captions { get; set; }
#endif
        /// <summary>The chunk_index property</summary>
        public int? ChunkIndex { get; set; }
        /// <summary>List of doc items references</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DocItems { get; set; }
#nullable restore
#else
        public List<string> DocItems { get; set; }
#endif
        /// <summary>The filename property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Filename { get; set; }
#nullable restore
#else
        public string Filename { get; set; }
#endif
        /// <summary>List of headings for this chunk</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_headings? Headings { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_headings Headings { get; set; }
#endif
        /// <summary>Additional metadata associated with this chunk</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Metadata { get; set; }
#nullable restore
#else
        public UntypedNode Metadata { get; set; }
#endif
        /// <summary>Number of tokens in the text, if the chunker is aware of tokens</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_num_tokens? NumTokens { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_num_tokens NumTokens { get; set; }
#endif
        /// <summary>Page numbers where this chunk content appears</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_page_numbers? PageNumbers { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_page_numbers PageNumbers { get; set; }
#endif
        /// <summary>Raw chunk text without additional formatting or context</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_raw_text? RawText { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_raw_text RawText { get; set; }
#endif
        /// <summary>The chunk text with structural context (headers, formatting)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.Models.ChunkedDocumentResultItem"/> and sets the default values.
        /// </summary>
        public ChunkedDocumentResultItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DoclingServe.Models.ChunkedDocumentResultItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DoclingServe.Models.ChunkedDocumentResultItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DoclingServe.Models.ChunkedDocumentResultItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "captions", n => { Captions = n.GetObjectValue<global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_captions>(global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_captions.CreateFromDiscriminatorValue); } },
                { "chunk_index", n => { ChunkIndex = n.GetIntValue(); } },
                { "doc_items", n => { DocItems = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "filename", n => { Filename = n.GetStringValue(); } },
                { "headings", n => { Headings = n.GetObjectValue<global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_headings>(global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_headings.CreateFromDiscriminatorValue); } },
                { "metadata", n => { Metadata = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "num_tokens", n => { NumTokens = n.GetObjectValue<global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_num_tokens>(global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_num_tokens.CreateFromDiscriminatorValue); } },
                { "page_numbers", n => { PageNumbers = n.GetObjectValue<global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_page_numbers>(global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_page_numbers.CreateFromDiscriminatorValue); } },
                { "raw_text", n => { RawText = n.GetObjectValue<global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_raw_text>(global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_raw_text.CreateFromDiscriminatorValue); } },
                { "text", n => { Text = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_captions>("captions", Captions);
            writer.WriteIntValue("chunk_index", ChunkIndex);
            writer.WriteCollectionOfPrimitiveValues<string>("doc_items", DocItems);
            writer.WriteStringValue("filename", Filename);
            writer.WriteObjectValue<global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_headings>("headings", Headings);
            writer.WriteObjectValue<UntypedNode>("metadata", Metadata);
            writer.WriteObjectValue<global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_num_tokens>("num_tokens", NumTokens);
            writer.WriteObjectValue<global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_page_numbers>("page_numbers", PageNumbers);
            writer.WriteObjectValue<global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_raw_text>("raw_text", RawText);
            writer.WriteStringValue("text", Text);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::DoclingServe.Models.ChunkedDocumentResultItem_captionsMember1"/>, List&lt;string&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ChunkedDocumentResultItem_captions : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.ChunkedDocumentResultItem_captionsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.ChunkedDocumentResultItem_captionsMember1? ChunkedDocumentResultItemCaptionsMember1 { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.ChunkedDocumentResultItem_captionsMember1 ChunkedDocumentResultItemCaptionsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type List&lt;string&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<string>? String { get; set; }
#nullable restore
#else
            public List<string> String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_captions"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_captions CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_captions();
                if(parseNode.GetCollectionOfPrimitiveValues<string>()?.AsList() is List<string> stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ChunkedDocumentResultItemCaptionsMember1 = new global::DoclingServe.Models.ChunkedDocumentResultItem_captionsMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ChunkedDocumentResultItemCaptionsMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ChunkedDocumentResultItemCaptionsMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<string>(null, String);
                }
                else {
                    writer.WriteObjectValue<global::DoclingServe.Models.ChunkedDocumentResultItem_captionsMember1>(null, ChunkedDocumentResultItemCaptionsMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::DoclingServe.Models.ChunkedDocumentResultItem_headingsMember1"/>, List&lt;string&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ChunkedDocumentResultItem_headings : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.ChunkedDocumentResultItem_headingsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.ChunkedDocumentResultItem_headingsMember1? ChunkedDocumentResultItemHeadingsMember1 { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.ChunkedDocumentResultItem_headingsMember1 ChunkedDocumentResultItemHeadingsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type List&lt;string&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<string>? String { get; set; }
#nullable restore
#else
            public List<string> String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_headings"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_headings CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_headings();
                if(parseNode.GetCollectionOfPrimitiveValues<string>()?.AsList() is List<string> stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ChunkedDocumentResultItemHeadingsMember1 = new global::DoclingServe.Models.ChunkedDocumentResultItem_headingsMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ChunkedDocumentResultItemHeadingsMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ChunkedDocumentResultItemHeadingsMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<string>(null, String);
                }
                else {
                    writer.WriteObjectValue<global::DoclingServe.Models.ChunkedDocumentResultItem_headingsMember1>(null, ChunkedDocumentResultItemHeadingsMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::DoclingServe.Models.ChunkedDocumentResultItem_num_tokensMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ChunkedDocumentResultItem_num_tokens : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.ChunkedDocumentResultItem_num_tokensMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.ChunkedDocumentResultItem_num_tokensMember1? ChunkedDocumentResultItemNumTokensMember1 { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.ChunkedDocumentResultItem_num_tokensMember1 ChunkedDocumentResultItemNumTokensMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_num_tokens"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_num_tokens CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_num_tokens();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.ChunkedDocumentResultItemNumTokensMember1 = new global::DoclingServe.Models.ChunkedDocumentResultItem_num_tokensMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ChunkedDocumentResultItemNumTokensMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ChunkedDocumentResultItemNumTokensMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::DoclingServe.Models.ChunkedDocumentResultItem_num_tokensMember1>(null, ChunkedDocumentResultItemNumTokensMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::DoclingServe.Models.ChunkedDocumentResultItem_page_numbersMember1"/>, List&lt;int&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ChunkedDocumentResultItem_page_numbers : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.ChunkedDocumentResultItem_page_numbersMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.ChunkedDocumentResultItem_page_numbersMember1? ChunkedDocumentResultItemPageNumbersMember1 { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.ChunkedDocumentResultItem_page_numbersMember1 ChunkedDocumentResultItemPageNumbersMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type List&lt;int&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<int?>? Integer { get; set; }
#nullable restore
#else
            public List<int?> Integer { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_page_numbers"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_page_numbers CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_page_numbers();
                if(parseNode.GetCollectionOfPrimitiveValues<int?>()?.AsList() is List<int?> integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.ChunkedDocumentResultItemPageNumbersMember1 = new global::DoclingServe.Models.ChunkedDocumentResultItem_page_numbersMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ChunkedDocumentResultItemPageNumbersMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ChunkedDocumentResultItemPageNumbersMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<int?>(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::DoclingServe.Models.ChunkedDocumentResultItem_page_numbersMember1>(null, ChunkedDocumentResultItemPageNumbersMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::DoclingServe.Models.ChunkedDocumentResultItem_raw_textMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ChunkedDocumentResultItem_raw_text : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.ChunkedDocumentResultItem_raw_textMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.ChunkedDocumentResultItem_raw_textMember1? ChunkedDocumentResultItemRawTextMember1 { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.ChunkedDocumentResultItem_raw_textMember1 ChunkedDocumentResultItemRawTextMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_raw_text"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_raw_text CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::DoclingServe.Models.ChunkedDocumentResultItem.ChunkedDocumentResultItem_raw_text();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ChunkedDocumentResultItemRawTextMember1 = new global::DoclingServe.Models.ChunkedDocumentResultItem_raw_textMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ChunkedDocumentResultItemRawTextMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ChunkedDocumentResultItemRawTextMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::DoclingServe.Models.ChunkedDocumentResultItem_raw_textMember1>(null, ChunkedDocumentResultItemRawTextMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
