// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    /// <summary>CodeLanguageLabel.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CodeLanguageLabel
    {
        [EnumMember(Value = "Ada")]
        #pragma warning disable CS1591
        Ada,
        #pragma warning restore CS1591
        [EnumMember(Value = "Awk")]
        #pragma warning disable CS1591
        Awk,
        #pragma warning restore CS1591
        [EnumMember(Value = "Bash")]
        #pragma warning disable CS1591
        Bash,
        #pragma warning restore CS1591
        [EnumMember(Value = "bc")]
        #pragma warning disable CS1591
        Bc,
        #pragma warning restore CS1591
        [EnumMember(Value = "C")]
        #pragma warning disable CS1591
        C,
        #pragma warning restore CS1591
        [EnumMember(Value = "C++")]
        #pragma warning disable CS1591
        C_plus__plus,
        #pragma warning restore CS1591
        [EnumMember(Value = "CMake")]
        #pragma warning disable CS1591
        CMake,
        #pragma warning restore CS1591
        [EnumMember(Value = "COBOL")]
        #pragma warning disable CS1591
        COBOL,
        #pragma warning restore CS1591
        [EnumMember(Value = "CSS")]
        #pragma warning disable CS1591
        CSS,
        #pragma warning restore CS1591
        [EnumMember(Value = "Ceylon")]
        #pragma warning disable CS1591
        Ceylon,
        #pragma warning restore CS1591
        [EnumMember(Value = "Clojure")]
        #pragma warning disable CS1591
        Clojure,
        #pragma warning restore CS1591
        [EnumMember(Value = "Crystal")]
        #pragma warning disable CS1591
        Crystal,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cuda")]
        #pragma warning disable CS1591
        Cuda,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cython")]
        #pragma warning disable CS1591
        Cython,
        #pragma warning restore CS1591
        [EnumMember(Value = "D")]
        #pragma warning disable CS1591
        D,
        #pragma warning restore CS1591
        [EnumMember(Value = "Dart")]
        #pragma warning disable CS1591
        Dart,
        #pragma warning restore CS1591
        [EnumMember(Value = "dc")]
        #pragma warning disable CS1591
        Dc,
        #pragma warning restore CS1591
        [EnumMember(Value = "Dockerfile")]
        #pragma warning disable CS1591
        Dockerfile,
        #pragma warning restore CS1591
        [EnumMember(Value = "Elixir")]
        #pragma warning disable CS1591
        Elixir,
        #pragma warning restore CS1591
        [EnumMember(Value = "Erlang")]
        #pragma warning disable CS1591
        Erlang,
        #pragma warning restore CS1591
        [EnumMember(Value = "FORTRAN")]
        #pragma warning disable CS1591
        FORTRAN,
        #pragma warning restore CS1591
        [EnumMember(Value = "Forth")]
        #pragma warning disable CS1591
        Forth,
        #pragma warning restore CS1591
        [EnumMember(Value = "Go")]
        #pragma warning disable CS1591
        Go,
        #pragma warning restore CS1591
        [EnumMember(Value = "HTML")]
        #pragma warning disable CS1591
        HTML,
        #pragma warning restore CS1591
        [EnumMember(Value = "Haskell")]
        #pragma warning disable CS1591
        Haskell,
        #pragma warning restore CS1591
        [EnumMember(Value = "Haxe")]
        #pragma warning disable CS1591
        Haxe,
        #pragma warning restore CS1591
        [EnumMember(Value = "Java")]
        #pragma warning disable CS1591
        Java,
        #pragma warning restore CS1591
        [EnumMember(Value = "JavaScript")]
        #pragma warning disable CS1591
        JavaScript,
        #pragma warning restore CS1591
        [EnumMember(Value = "Julia")]
        #pragma warning disable CS1591
        Julia,
        #pragma warning restore CS1591
        [EnumMember(Value = "Kotlin")]
        #pragma warning disable CS1591
        Kotlin,
        #pragma warning restore CS1591
        [EnumMember(Value = "Lisp")]
        #pragma warning disable CS1591
        Lisp,
        #pragma warning restore CS1591
        [EnumMember(Value = "Lua")]
        #pragma warning disable CS1591
        Lua,
        #pragma warning restore CS1591
        [EnumMember(Value = "Matlab")]
        #pragma warning disable CS1591
        Matlab,
        #pragma warning restore CS1591
        [EnumMember(Value = "MoonScript")]
        #pragma warning disable CS1591
        MoonScript,
        #pragma warning restore CS1591
        [EnumMember(Value = "Nim")]
        #pragma warning disable CS1591
        Nim,
        #pragma warning restore CS1591
        [EnumMember(Value = "OCaml")]
        #pragma warning disable CS1591
        OCaml,
        #pragma warning restore CS1591
        [EnumMember(Value = "ObjectiveC")]
        #pragma warning disable CS1591
        ObjectiveC,
        #pragma warning restore CS1591
        [EnumMember(Value = "Octave")]
        #pragma warning disable CS1591
        Octave,
        #pragma warning restore CS1591
        [EnumMember(Value = "PHP")]
        #pragma warning disable CS1591
        PHP,
        #pragma warning restore CS1591
        [EnumMember(Value = "Pascal")]
        #pragma warning disable CS1591
        Pascal,
        #pragma warning restore CS1591
        [EnumMember(Value = "Perl")]
        #pragma warning disable CS1591
        Perl,
        #pragma warning restore CS1591
        [EnumMember(Value = "Prolog")]
        #pragma warning disable CS1591
        Prolog,
        #pragma warning restore CS1591
        [EnumMember(Value = "Python")]
        #pragma warning disable CS1591
        Python,
        #pragma warning restore CS1591
        [EnumMember(Value = "Racket")]
        #pragma warning disable CS1591
        Racket,
        #pragma warning restore CS1591
        [EnumMember(Value = "Ruby")]
        #pragma warning disable CS1591
        Ruby,
        #pragma warning restore CS1591
        [EnumMember(Value = "Rust")]
        #pragma warning disable CS1591
        Rust,
        #pragma warning restore CS1591
        [EnumMember(Value = "SML")]
        #pragma warning disable CS1591
        SML,
        #pragma warning restore CS1591
        [EnumMember(Value = "SQL")]
        #pragma warning disable CS1591
        SQL,
        #pragma warning restore CS1591
        [EnumMember(Value = "Scala")]
        #pragma warning disable CS1591
        Scala,
        #pragma warning restore CS1591
        [EnumMember(Value = "Scheme")]
        #pragma warning disable CS1591
        Scheme,
        #pragma warning restore CS1591
        [EnumMember(Value = "Swift")]
        #pragma warning disable CS1591
        Swift,
        #pragma warning restore CS1591
        [EnumMember(Value = "TypeScript")]
        #pragma warning disable CS1591
        TypeScript,
        #pragma warning restore CS1591
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "VisualBasic")]
        #pragma warning disable CS1591
        VisualBasic,
        #pragma warning restore CS1591
        [EnumMember(Value = "XML")]
        #pragma warning disable CS1591
        XML,
        #pragma warning restore CS1591
        [EnumMember(Value = "YAML")]
        #pragma warning disable CS1591
        YAML,
        #pragma warning restore CS1591
    }
}
