// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DoclingServe.Models
{
    /// <summary>
    /// CodeItem.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CodeItem : IParsable
    {
        /// <summary>The captions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DoclingServe.Models.RefItem>? Captions { get; set; }
#nullable restore
#else
        public List<global::DoclingServe.Models.RefItem> Captions { get; set; }
#endif
        /// <summary>The children property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DoclingServe.Models.RefItem>? Children { get; set; }
#nullable restore
#else
        public List<global::DoclingServe.Models.RefItem> Children { get; set; }
#endif
        /// <summary>CodeLanguageLabel.</summary>
        public global::DoclingServe.Models.CodeLanguageLabel? CodeLanguage { get; set; }
        /// <summary>ContentLayer.</summary>
        public global::DoclingServe.Models.ContentLayer? ContentLayer { get; set; }
        /// <summary>The footnotes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DoclingServe.Models.RefItem>? Footnotes { get; set; }
#nullable restore
#else
        public List<global::DoclingServe.Models.RefItem> Footnotes { get; set; }
#endif
        /// <summary>The formatting property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.Formatting? Formatting { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.Formatting Formatting { get; set; }
#endif
        /// <summary>The hyperlink property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.CodeItem.CodeItem_hyperlink? Hyperlink { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.CodeItem.CodeItem_hyperlink Hyperlink { get; set; }
#endif
        /// <summary>The image property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.ImageRef? Image { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.ImageRef Image { get; set; }
#endif
        /// <summary>The label property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>The meta property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.FloatingMeta? Meta { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.FloatingMeta Meta { get; set; }
#endif
        /// <summary>The orig property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Orig { get; set; }
#nullable restore
#else
        public string Orig { get; set; }
#endif
        /// <summary>The parent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.RefItem? Parent { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.RefItem Parent { get; set; }
#endif
        /// <summary>The prov property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DoclingServe.Models.ProvenanceItem>? Prov { get; set; }
#nullable restore
#else
        public List<global::DoclingServe.Models.ProvenanceItem> Prov { get; set; }
#endif
        /// <summary>The references property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DoclingServe.Models.RefItem>? References { get; set; }
#nullable restore
#else
        public List<global::DoclingServe.Models.RefItem> References { get; set; }
#endif
        /// <summary>The self_ref property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SelfRef { get; set; }
#nullable restore
#else
        public string SelfRef { get; set; }
#endif
        /// <summary>The text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.Models.CodeItem"/> and sets the default values.
        /// </summary>
        public CodeItem()
        {
            CodeLanguage = global::DoclingServe.Models.CodeLanguageLabel.Unknown;
            ContentLayer = global::DoclingServe.Models.ContentLayer.Body;
            Label = "code";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DoclingServe.Models.CodeItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DoclingServe.Models.CodeItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DoclingServe.Models.CodeItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "captions", n => { Captions = n.GetCollectionOfObjectValues<global::DoclingServe.Models.RefItem>(global::DoclingServe.Models.RefItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "children", n => { Children = n.GetCollectionOfObjectValues<global::DoclingServe.Models.RefItem>(global::DoclingServe.Models.RefItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "code_language", n => { CodeLanguage = n.GetEnumValue<global::DoclingServe.Models.CodeLanguageLabel>(); } },
                { "content_layer", n => { ContentLayer = n.GetEnumValue<global::DoclingServe.Models.ContentLayer>(); } },
                { "footnotes", n => { Footnotes = n.GetCollectionOfObjectValues<global::DoclingServe.Models.RefItem>(global::DoclingServe.Models.RefItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "formatting", n => { Formatting = n.GetObjectValue<global::DoclingServe.Models.Formatting>(global::DoclingServe.Models.Formatting.CreateFromDiscriminatorValue); } },
                { "hyperlink", n => { Hyperlink = n.GetObjectValue<global::DoclingServe.Models.CodeItem.CodeItem_hyperlink>(global::DoclingServe.Models.CodeItem.CodeItem_hyperlink.CreateFromDiscriminatorValue); } },
                { "image", n => { Image = n.GetObjectValue<global::DoclingServe.Models.ImageRef>(global::DoclingServe.Models.ImageRef.CreateFromDiscriminatorValue); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "meta", n => { Meta = n.GetObjectValue<global::DoclingServe.Models.FloatingMeta>(global::DoclingServe.Models.FloatingMeta.CreateFromDiscriminatorValue); } },
                { "orig", n => { Orig = n.GetStringValue(); } },
                { "parent", n => { Parent = n.GetObjectValue<global::DoclingServe.Models.RefItem>(global::DoclingServe.Models.RefItem.CreateFromDiscriminatorValue); } },
                { "prov", n => { Prov = n.GetCollectionOfObjectValues<global::DoclingServe.Models.ProvenanceItem>(global::DoclingServe.Models.ProvenanceItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "references", n => { References = n.GetCollectionOfObjectValues<global::DoclingServe.Models.RefItem>(global::DoclingServe.Models.RefItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "self_ref", n => { SelfRef = n.GetStringValue(); } },
                { "text", n => { Text = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::DoclingServe.Models.RefItem>("captions", Captions);
            writer.WriteCollectionOfObjectValues<global::DoclingServe.Models.RefItem>("children", Children);
            writer.WriteEnumValue<global::DoclingServe.Models.CodeLanguageLabel>("code_language", CodeLanguage);
            writer.WriteEnumValue<global::DoclingServe.Models.ContentLayer>("content_layer", ContentLayer);
            writer.WriteCollectionOfObjectValues<global::DoclingServe.Models.RefItem>("footnotes", Footnotes);
            writer.WriteObjectValue<global::DoclingServe.Models.Formatting>("formatting", Formatting);
            writer.WriteObjectValue<global::DoclingServe.Models.CodeItem.CodeItem_hyperlink>("hyperlink", Hyperlink);
            writer.WriteObjectValue<global::DoclingServe.Models.ImageRef>("image", Image);
            writer.WriteStringValue("label", Label);
            writer.WriteObjectValue<global::DoclingServe.Models.FloatingMeta>("meta", Meta);
            writer.WriteStringValue("orig", Orig);
            writer.WriteObjectValue<global::DoclingServe.Models.RefItem>("parent", Parent);
            writer.WriteCollectionOfObjectValues<global::DoclingServe.Models.ProvenanceItem>("prov", Prov);
            writer.WriteCollectionOfObjectValues<global::DoclingServe.Models.RefItem>("references", References);
            writer.WriteStringValue("self_ref", SelfRef);
            writer.WriteStringValue("text", Text);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::DoclingServe.Models.CodeItem_hyperlinkMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CodeItem_hyperlink : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.CodeItem_hyperlinkMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.CodeItem_hyperlinkMember1? CodeItemHyperlinkMember1 { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.CodeItem_hyperlinkMember1 CodeItemHyperlinkMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::DoclingServe.Models.CodeItem.CodeItem_hyperlink"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::DoclingServe.Models.CodeItem.CodeItem_hyperlink CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::DoclingServe.Models.CodeItem.CodeItem_hyperlink();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.CodeItemHyperlinkMember1 = new global::DoclingServe.Models.CodeItem_hyperlinkMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CodeItemHyperlinkMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CodeItemHyperlinkMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::DoclingServe.Models.CodeItem_hyperlinkMember1>(null, CodeItemHyperlinkMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
