// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    /// <summary>ContentLayer.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ContentLayer
    {
        [EnumMember(Value = "body")]
        #pragma warning disable CS1591
        Body,
        #pragma warning restore CS1591
        [EnumMember(Value = "furniture")]
        #pragma warning disable CS1591
        Furniture,
        #pragma warning restore CS1591
        [EnumMember(Value = "background")]
        #pragma warning disable CS1591
        Background,
        #pragma warning restore CS1591
        [EnumMember(Value = "invisible")]
        #pragma warning disable CS1591
        Invisible,
        #pragma warning restore CS1591
        [EnumMember(Value = "notes")]
        #pragma warning disable CS1591
        Notes,
        #pragma warning restore CS1591
    }
}
