// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    /// <summary>CoordOrigin.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CoordOrigin
    {
        [EnumMember(Value = "TOPLEFT")]
        #pragma warning disable CS1591
        TOPLEFT,
        #pragma warning restore CS1591
        [EnumMember(Value = "BOTTOMLEFT")]
        #pragma warning disable CS1591
        BOTTOMLEFT,
        #pragma warning restore CS1591
    }
}
