// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DoclingComponentType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "document_backend")]
        #pragma warning disable CS1591
        Document_backend,
        #pragma warning restore CS1591
        [EnumMember(Value = "model")]
        #pragma warning disable CS1591
        Model,
        #pragma warning restore CS1591
        [EnumMember(Value = "doc_assembler")]
        #pragma warning disable CS1591
        Doc_assembler,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_input")]
        #pragma warning disable CS1591
        User_input,
        #pragma warning restore CS1591
    }
}
