// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DoclingServe.Models
{
    /// <summary>
    /// Container of all exported content.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExportResult : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The content property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.ExportDocumentResponse? Content { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.ExportDocumentResponse Content { get; set; }
#endif
        /// <summary>The errors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DoclingServe.Models.ErrorItem>? Errors { get; set; }
#nullable restore
#else
        public List<global::DoclingServe.Models.ErrorItem> Errors { get; set; }
#endif
        /// <summary>The kind property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Kind { get; set; }
#nullable restore
#else
        public string Kind { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::DoclingServe.Models.ConversionStatus? Status { get; set; }
        /// <summary>The timings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.ExportResult_timings? Timings { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.ExportResult_timings Timings { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.Models.ExportResult"/> and sets the default values.
        /// </summary>
        public ExportResult()
        {
            AdditionalData = new Dictionary<string, object>();
            Kind = "ExportResult";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DoclingServe.Models.ExportResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DoclingServe.Models.ExportResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DoclingServe.Models.ExportResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "content", n => { Content = n.GetObjectValue<global::DoclingServe.Models.ExportDocumentResponse>(global::DoclingServe.Models.ExportDocumentResponse.CreateFromDiscriminatorValue); } },
                { "errors", n => { Errors = n.GetCollectionOfObjectValues<global::DoclingServe.Models.ErrorItem>(global::DoclingServe.Models.ErrorItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "kind", n => { Kind = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::DoclingServe.Models.ConversionStatus>(); } },
                { "timings", n => { Timings = n.GetObjectValue<global::DoclingServe.Models.ExportResult_timings>(global::DoclingServe.Models.ExportResult_timings.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::DoclingServe.Models.ExportDocumentResponse>("content", Content);
            writer.WriteCollectionOfObjectValues<global::DoclingServe.Models.ErrorItem>("errors", Errors);
            writer.WriteStringValue("kind", Kind);
            writer.WriteEnumValue<global::DoclingServe.Models.ConversionStatus>("status", Status);
            writer.WriteObjectValue<global::DoclingServe.Models.ExportResult_timings>("timings", Timings);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
