// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DoclingServe.Models
{
    /// <summary>
    /// Formatting.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Formatting : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bold property</summary>
        public bool? Bold { get; set; }
        /// <summary>The italic property</summary>
        public bool? Italic { get; set; }
        /// <summary>Text script position.</summary>
        public global::DoclingServe.Models.Script? Script { get; set; }
        /// <summary>The strikethrough property</summary>
        public bool? Strikethrough { get; set; }
        /// <summary>The underline property</summary>
        public bool? Underline { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.Models.Formatting"/> and sets the default values.
        /// </summary>
        public Formatting()
        {
            AdditionalData = new Dictionary<string, object>();
            Script = global::DoclingServe.Models.Script.Baseline;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DoclingServe.Models.Formatting"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DoclingServe.Models.Formatting CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DoclingServe.Models.Formatting();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bold", n => { Bold = n.GetBoolValue(); } },
                { "italic", n => { Italic = n.GetBoolValue(); } },
                { "script", n => { Script = n.GetEnumValue<global::DoclingServe.Models.Script>(); } },
                { "strikethrough", n => { Strikethrough = n.GetBoolValue(); } },
                { "underline", n => { Underline = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("bold", Bold);
            writer.WriteBoolValue("italic", Italic);
            writer.WriteEnumValue<global::DoclingServe.Models.Script>("script", Script);
            writer.WriteBoolValue("strikethrough", Strikethrough);
            writer.WriteBoolValue("underline", Underline);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
