// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DoclingServe.Models
{
    /// <summary>
    /// GraphCell.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GraphCell : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cell_id property</summary>
        public int? CellId { get; set; }
        /// <summary>The item_ref property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.RefItem? ItemRef { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.RefItem ItemRef { get; set; }
#endif
        /// <summary>GraphCellLabel.</summary>
        public global::DoclingServe.Models.GraphCellLabel? Label { get; set; }
        /// <summary>The orig property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Orig { get; set; }
#nullable restore
#else
        public string Orig { get; set; }
#endif
        /// <summary>The prov property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.ProvenanceItem? Prov { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.ProvenanceItem Prov { get; set; }
#endif
        /// <summary>The text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.Models.GraphCell"/> and sets the default values.
        /// </summary>
        public GraphCell()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DoclingServe.Models.GraphCell"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DoclingServe.Models.GraphCell CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DoclingServe.Models.GraphCell();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cell_id", n => { CellId = n.GetIntValue(); } },
                { "item_ref", n => { ItemRef = n.GetObjectValue<global::DoclingServe.Models.RefItem>(global::DoclingServe.Models.RefItem.CreateFromDiscriminatorValue); } },
                { "label", n => { Label = n.GetEnumValue<global::DoclingServe.Models.GraphCellLabel>(); } },
                { "orig", n => { Orig = n.GetStringValue(); } },
                { "prov", n => { Prov = n.GetObjectValue<global::DoclingServe.Models.ProvenanceItem>(global::DoclingServe.Models.ProvenanceItem.CreateFromDiscriminatorValue); } },
                { "text", n => { Text = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("cell_id", CellId);
            writer.WriteObjectValue<global::DoclingServe.Models.RefItem>("item_ref", ItemRef);
            writer.WriteEnumValue<global::DoclingServe.Models.GraphCellLabel>("label", Label);
            writer.WriteStringValue("orig", Orig);
            writer.WriteObjectValue<global::DoclingServe.Models.ProvenanceItem>("prov", Prov);
            writer.WriteStringValue("text", Text);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
