// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    /// <summary>GraphLinkLabel.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GraphLinkLabel
    {
        [EnumMember(Value = "unspecified")]
        #pragma warning disable CS1591
        Unspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "to_value")]
        #pragma warning disable CS1591
        To_value,
        #pragma warning restore CS1591
        [EnumMember(Value = "to_key")]
        #pragma warning disable CS1591
        To_key,
        #pragma warning restore CS1591
        [EnumMember(Value = "to_parent")]
        #pragma warning disable CS1591
        To_parent,
        #pragma warning restore CS1591
        [EnumMember(Value = "to_child")]
        #pragma warning disable CS1591
        To_child,
        #pragma warning restore CS1591
    }
}
