// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    /// <summary>GraphCellLabel.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GraphCellLabel
    {
        [EnumMember(Value = "unspecified")]
        #pragma warning disable CS1591
        Unspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "key")]
        #pragma warning disable CS1591
        Key,
        #pragma warning restore CS1591
        [EnumMember(Value = "value")]
        #pragma warning disable CS1591
        Value,
        #pragma warning restore CS1591
        [EnumMember(Value = "checkbox")]
        #pragma warning disable CS1591
        Checkbox,
        #pragma warning restore CS1591
    }
}
