// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    /// <summary>GroupLabel.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GroupLabel
    {
        [EnumMember(Value = "unspecified")]
        #pragma warning disable CS1591
        Unspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "list")]
        #pragma warning disable CS1591
        List,
        #pragma warning restore CS1591
        [EnumMember(Value = "ordered_list")]
        #pragma warning disable CS1591
        Ordered_list,
        #pragma warning restore CS1591
        [EnumMember(Value = "chapter")]
        #pragma warning disable CS1591
        Chapter,
        #pragma warning restore CS1591
        [EnumMember(Value = "section")]
        #pragma warning disable CS1591
        Section,
        #pragma warning restore CS1591
        [EnumMember(Value = "sheet")]
        #pragma warning disable CS1591
        Sheet,
        #pragma warning restore CS1591
        [EnumMember(Value = "slide")]
        #pragma warning disable CS1591
        Slide,
        #pragma warning restore CS1591
        [EnumMember(Value = "form_area")]
        #pragma warning disable CS1591
        Form_area,
        #pragma warning restore CS1591
        [EnumMember(Value = "key_value_area")]
        #pragma warning disable CS1591
        Key_value_area,
        #pragma warning restore CS1591
        [EnumMember(Value = "comment_section")]
        #pragma warning disable CS1591
        Comment_section,
        #pragma warning restore CS1591
        [EnumMember(Value = "inline")]
        #pragma warning disable CS1591
        Inline,
        #pragma warning restore CS1591
        [EnumMember(Value = "picture_area")]
        #pragma warning disable CS1591
        Picture_area,
        #pragma warning restore CS1591
    }
}
