// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DoclingServe.Models
{
    /// <summary>
    /// Options specific to the chunker.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HierarchicalChunkerOptions : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The chunker property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Chunker { get; set; }
#nullable restore
#else
        public string Chunker { get; set; }
#endif
        /// <summary>Include both raw_text and text (contextualized) in response. If False, only text is included.</summary>
        public bool? IncludeRawText { get; set; }
        /// <summary>Use markdown table format instead of triplets for table serialization.</summary>
        public bool? UseMarkdownTables { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.Models.HierarchicalChunkerOptions"/> and sets the default values.
        /// </summary>
        public HierarchicalChunkerOptions()
        {
            AdditionalData = new Dictionary<string, object>();
            Chunker = "hierarchical";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DoclingServe.Models.HierarchicalChunkerOptions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DoclingServe.Models.HierarchicalChunkerOptions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DoclingServe.Models.HierarchicalChunkerOptions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "chunker", n => { Chunker = n.GetStringValue(); } },
                { "include_raw_text", n => { IncludeRawText = n.GetBoolValue(); } },
                { "use_markdown_tables", n => { UseMarkdownTables = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("chunker", Chunker);
            writer.WriteBoolValue("include_raw_text", IncludeRawText);
            writer.WriteBoolValue("use_markdown_tables", UseMarkdownTables);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
