// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DoclingServe.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class HierarchicalChunkerOptionsDocumentsRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Options specific to the chunker.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.HierarchicalChunkerOptions? ChunkingOptions { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.HierarchicalChunkerOptions ChunkingOptions { get; set; }
#endif
        /// <summary>Conversion options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.ConvertDocumentsRequestOptions? ConvertOptions { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.ConvertDocumentsRequestOptions ConvertOptions { get; set; }
#endif
        /// <summary>If true, the output will include both the chunks and the converted document.</summary>
        public bool? IncludeConvertedDoc { get; set; }
        /// <summary>List of input document sources to process.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DoclingServe.Models.HierarchicalChunkerOptionsDocumentsRequest.HierarchicalChunkerOptionsDocumentsRequest_sources>? Sources { get; set; }
#nullable restore
#else
        public List<global::DoclingServe.Models.HierarchicalChunkerOptionsDocumentsRequest.HierarchicalChunkerOptionsDocumentsRequest_sources> Sources { get; set; }
#endif
        /// <summary>Specification for the type of output target.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.HierarchicalChunkerOptionsDocumentsRequest.HierarchicalChunkerOptionsDocumentsRequest_target? Target { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.HierarchicalChunkerOptionsDocumentsRequest.HierarchicalChunkerOptionsDocumentsRequest_target Target { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.Models.HierarchicalChunkerOptionsDocumentsRequest"/> and sets the default values.
        /// </summary>
        public HierarchicalChunkerOptionsDocumentsRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DoclingServe.Models.HierarchicalChunkerOptionsDocumentsRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DoclingServe.Models.HierarchicalChunkerOptionsDocumentsRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DoclingServe.Models.HierarchicalChunkerOptionsDocumentsRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "chunking_options", n => { ChunkingOptions = n.GetObjectValue<global::DoclingServe.Models.HierarchicalChunkerOptions>(global::DoclingServe.Models.HierarchicalChunkerOptions.CreateFromDiscriminatorValue); } },
                { "convert_options", n => { ConvertOptions = n.GetObjectValue<global::DoclingServe.Models.ConvertDocumentsRequestOptions>(global::DoclingServe.Models.ConvertDocumentsRequestOptions.CreateFromDiscriminatorValue); } },
                { "include_converted_doc", n => { IncludeConvertedDoc = n.GetBoolValue(); } },
                { "sources", n => { Sources = n.GetCollectionOfObjectValues<global::DoclingServe.Models.HierarchicalChunkerOptionsDocumentsRequest.HierarchicalChunkerOptionsDocumentsRequest_sources>(global::DoclingServe.Models.HierarchicalChunkerOptionsDocumentsRequest.HierarchicalChunkerOptionsDocumentsRequest_sources.CreateFromDiscriminatorValue)?.AsList(); } },
                { "target", n => { Target = n.GetObjectValue<global::DoclingServe.Models.HierarchicalChunkerOptionsDocumentsRequest.HierarchicalChunkerOptionsDocumentsRequest_target>(global::DoclingServe.Models.HierarchicalChunkerOptionsDocumentsRequest.HierarchicalChunkerOptionsDocumentsRequest_target.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::DoclingServe.Models.HierarchicalChunkerOptions>("chunking_options", ChunkingOptions);
            writer.WriteObjectValue<global::DoclingServe.Models.ConvertDocumentsRequestOptions>("convert_options", ConvertOptions);
            writer.WriteBoolValue("include_converted_doc", IncludeConvertedDoc);
            writer.WriteCollectionOfObjectValues<global::DoclingServe.Models.HierarchicalChunkerOptionsDocumentsRequest.HierarchicalChunkerOptionsDocumentsRequest_sources>("sources", Sources);
            writer.WriteObjectValue<global::DoclingServe.Models.HierarchicalChunkerOptionsDocumentsRequest.HierarchicalChunkerOptionsDocumentsRequest_target>("target", Target);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::DoclingServe.Models.FileSourceRequest"/>, <see cref="global::DoclingServe.Models.HttpSourceRequest"/>, <see cref="global::DoclingServe.Models.S3SourceRequest"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class HierarchicalChunkerOptionsDocumentsRequest_sources : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.FileSourceRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.FileSourceRequest? FileSourceRequest { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.FileSourceRequest FileSourceRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.HttpSourceRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.HttpSourceRequest? HttpSourceRequest { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.HttpSourceRequest HttpSourceRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.S3SourceRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.S3SourceRequest? S3SourceRequest { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.S3SourceRequest S3SourceRequest { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::DoclingServe.Models.HierarchicalChunkerOptionsDocumentsRequest.HierarchicalChunkerOptionsDocumentsRequest_sources"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::DoclingServe.Models.HierarchicalChunkerOptionsDocumentsRequest.HierarchicalChunkerOptionsDocumentsRequest_sources CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("kind")?.GetStringValue();
                var result = new global::DoclingServe.Models.HierarchicalChunkerOptionsDocumentsRequest.HierarchicalChunkerOptionsDocumentsRequest_sources();
                if("file".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.FileSourceRequest = new global::DoclingServe.Models.FileSourceRequest();
                }
                else if("http".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.HttpSourceRequest = new global::DoclingServe.Models.HttpSourceRequest();
                }
                else if("s3".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.S3SourceRequest = new global::DoclingServe.Models.S3SourceRequest();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(FileSourceRequest != null)
                {
                    return FileSourceRequest.GetFieldDeserializers();
                }
                else if(HttpSourceRequest != null)
                {
                    return HttpSourceRequest.GetFieldDeserializers();
                }
                else if(S3SourceRequest != null)
                {
                    return S3SourceRequest.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(FileSourceRequest != null)
                {
                    writer.WriteObjectValue<global::DoclingServe.Models.FileSourceRequest>(null, FileSourceRequest);
                }
                else if(HttpSourceRequest != null)
                {
                    writer.WriteObjectValue<global::DoclingServe.Models.HttpSourceRequest>(null, HttpSourceRequest);
                }
                else if(S3SourceRequest != null)
                {
                    writer.WriteObjectValue<global::DoclingServe.Models.S3SourceRequest>(null, S3SourceRequest);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::DoclingServe.Models.InBodyTarget"/>, <see cref="global::DoclingServe.Models.PutTarget"/>, <see cref="global::DoclingServe.Models.S3Target"/>, <see cref="global::DoclingServe.Models.ZipTarget"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class HierarchicalChunkerOptionsDocumentsRequest_target : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.InBodyTarget"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.InBodyTarget? InBodyTarget { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.InBodyTarget InBodyTarget { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.PutTarget"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.PutTarget? PutTarget { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.PutTarget PutTarget { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.S3Target"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.S3Target? S3Target { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.S3Target S3Target { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.ZipTarget"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.ZipTarget? ZipTarget { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.ZipTarget ZipTarget { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::DoclingServe.Models.HierarchicalChunkerOptionsDocumentsRequest.HierarchicalChunkerOptionsDocumentsRequest_target"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::DoclingServe.Models.HierarchicalChunkerOptionsDocumentsRequest.HierarchicalChunkerOptionsDocumentsRequest_target CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("kind")?.GetStringValue();
                var result = new global::DoclingServe.Models.HierarchicalChunkerOptionsDocumentsRequest.HierarchicalChunkerOptionsDocumentsRequest_target();
                if("inbody".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.InBodyTarget = new global::DoclingServe.Models.InBodyTarget();
                }
                else if("put".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PutTarget = new global::DoclingServe.Models.PutTarget();
                }
                else if("s3".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.S3Target = new global::DoclingServe.Models.S3Target();
                }
                else if("zip".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ZipTarget = new global::DoclingServe.Models.ZipTarget();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(InBodyTarget != null)
                {
                    return InBodyTarget.GetFieldDeserializers();
                }
                else if(PutTarget != null)
                {
                    return PutTarget.GetFieldDeserializers();
                }
                else if(S3Target != null)
                {
                    return S3Target.GetFieldDeserializers();
                }
                else if(ZipTarget != null)
                {
                    return ZipTarget.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(InBodyTarget != null)
                {
                    writer.WriteObjectValue<global::DoclingServe.Models.InBodyTarget>(null, InBodyTarget);
                }
                else if(PutTarget != null)
                {
                    writer.WriteObjectValue<global::DoclingServe.Models.PutTarget>(null, PutTarget);
                }
                else if(S3Target != null)
                {
                    writer.WriteObjectValue<global::DoclingServe.Models.S3Target>(null, S3Target);
                }
                else if(ZipTarget != null)
                {
                    writer.WriteObjectValue<global::DoclingServe.Models.ZipTarget>(null, ZipTarget);
                }
            }
        }
    }
}
#pragma warning restore CS0618
