// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DoclingServe.Models
{
    /// <summary>
    /// Options specific to the chunker.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HybridChunkerOptions : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The chunker property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Chunker { get; set; }
#nullable restore
#else
        public string Chunker { get; set; }
#endif
        /// <summary>Include both raw_text and text (contextualized) in response. If False, only text is included.</summary>
        public bool? IncludeRawText { get; set; }
        /// <summary>Maximum number of tokens per chunk. When left to none, the value is automatically extracted from the tokenizer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.HybridChunkerOptions.HybridChunkerOptions_max_tokens? MaxTokens { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.HybridChunkerOptions.HybridChunkerOptions_max_tokens MaxTokens { get; set; }
#endif
        /// <summary>Merge undersized successive chunks with same headings.</summary>
        public bool? MergePeers { get; set; }
        /// <summary>HuggingFace model name for custom tokenization. If not specified, uses &apos;sentence-transformers/all-MiniLM-L6-v2&apos; as default.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tokenizer { get; set; }
#nullable restore
#else
        public string Tokenizer { get; set; }
#endif
        /// <summary>Use markdown table format instead of triplets for table serialization.</summary>
        public bool? UseMarkdownTables { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.Models.HybridChunkerOptions"/> and sets the default values.
        /// </summary>
        public HybridChunkerOptions()
        {
            AdditionalData = new Dictionary<string, object>();
            Chunker = "hybrid";
            Tokenizer = "sentence-transformers/all-MiniLM-L6-v2";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DoclingServe.Models.HybridChunkerOptions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DoclingServe.Models.HybridChunkerOptions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DoclingServe.Models.HybridChunkerOptions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "chunker", n => { Chunker = n.GetStringValue(); } },
                { "include_raw_text", n => { IncludeRawText = n.GetBoolValue(); } },
                { "max_tokens", n => { MaxTokens = n.GetObjectValue<global::DoclingServe.Models.HybridChunkerOptions.HybridChunkerOptions_max_tokens>(global::DoclingServe.Models.HybridChunkerOptions.HybridChunkerOptions_max_tokens.CreateFromDiscriminatorValue); } },
                { "merge_peers", n => { MergePeers = n.GetBoolValue(); } },
                { "tokenizer", n => { Tokenizer = n.GetStringValue(); } },
                { "use_markdown_tables", n => { UseMarkdownTables = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("chunker", Chunker);
            writer.WriteBoolValue("include_raw_text", IncludeRawText);
            writer.WriteObjectValue<global::DoclingServe.Models.HybridChunkerOptions.HybridChunkerOptions_max_tokens>("max_tokens", MaxTokens);
            writer.WriteBoolValue("merge_peers", MergePeers);
            writer.WriteStringValue("tokenizer", Tokenizer);
            writer.WriteBoolValue("use_markdown_tables", UseMarkdownTables);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::DoclingServe.Models.HybridChunkerOptions_max_tokensMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class HybridChunkerOptions_max_tokens : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.HybridChunkerOptions_max_tokensMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.HybridChunkerOptions_max_tokensMember1? HybridChunkerOptionsMaxTokensMember1 { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.HybridChunkerOptions_max_tokensMember1 HybridChunkerOptionsMaxTokensMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::DoclingServe.Models.HybridChunkerOptions.HybridChunkerOptions_max_tokens"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::DoclingServe.Models.HybridChunkerOptions.HybridChunkerOptions_max_tokens CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::DoclingServe.Models.HybridChunkerOptions.HybridChunkerOptions_max_tokens();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.HybridChunkerOptionsMaxTokensMember1 = new global::DoclingServe.Models.HybridChunkerOptions_max_tokensMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(HybridChunkerOptionsMaxTokensMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(HybridChunkerOptionsMaxTokensMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::DoclingServe.Models.HybridChunkerOptions_max_tokensMember1>(null, HybridChunkerOptionsMaxTokensMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
