// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    /// <summary>Image export mode for the document (in case of JSON, Markdown or HTML). Allowed values: placeholder, embedded, referenced. Optional, defaults to Embedded.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ImageRefMode
    {
        [EnumMember(Value = "placeholder")]
        #pragma warning disable CS1591
        Placeholder,
        #pragma warning restore CS1591
        [EnumMember(Value = "embedded")]
        #pragma warning disable CS1591
        Embedded,
        #pragma warning restore CS1591
        [EnumMember(Value = "referenced")]
        #pragma warning disable CS1591
        Referenced,
        #pragma warning restore CS1591
    }
}
