// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    /// <summary>Inference framework to use.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InferenceFramework
    {
        [EnumMember(Value = "mlx")]
        #pragma warning disable CS1591
        Mlx,
        #pragma warning restore CS1591
        [EnumMember(Value = "transformers")]
        #pragma warning disable CS1591
        Transformers,
        #pragma warning restore CS1591
        [EnumMember(Value = "vllm")]
        #pragma warning disable CS1591
        Vllm,
        #pragma warning restore CS1591
    }
}
