// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    /// <summary>A document format supported by document backend parsers.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InputFormat
    {
        [EnumMember(Value = "docx")]
        #pragma warning disable CS1591
        Docx,
        #pragma warning restore CS1591
        [EnumMember(Value = "pptx")]
        #pragma warning disable CS1591
        Pptx,
        #pragma warning restore CS1591
        [EnumMember(Value = "html")]
        #pragma warning disable CS1591
        Html,
        #pragma warning restore CS1591
        [EnumMember(Value = "image")]
        #pragma warning disable CS1591
        Image,
        #pragma warning restore CS1591
        [EnumMember(Value = "pdf")]
        #pragma warning disable CS1591
        Pdf,
        #pragma warning restore CS1591
        [EnumMember(Value = "asciidoc")]
        #pragma warning disable CS1591
        Asciidoc,
        #pragma warning restore CS1591
        [EnumMember(Value = "md")]
        #pragma warning disable CS1591
        Md,
        #pragma warning restore CS1591
        [EnumMember(Value = "csv")]
        #pragma warning disable CS1591
        Csv,
        #pragma warning restore CS1591
        [EnumMember(Value = "xlsx")]
        #pragma warning disable CS1591
        Xlsx,
        #pragma warning restore CS1591
        [EnumMember(Value = "xml_uspto")]
        #pragma warning disable CS1591
        Xml_uspto,
        #pragma warning restore CS1591
        [EnumMember(Value = "xml_jats")]
        #pragma warning disable CS1591
        Xml_jats,
        #pragma warning restore CS1591
        [EnumMember(Value = "mets_gbs")]
        #pragma warning disable CS1591
        Mets_gbs,
        #pragma warning restore CS1591
        [EnumMember(Value = "json_docling")]
        #pragma warning disable CS1591
        Json_docling,
        #pragma warning restore CS1591
        [EnumMember(Value = "audio")]
        #pragma warning disable CS1591
        Audio,
        #pragma warning restore CS1591
        [EnumMember(Value = "vtt")]
        #pragma warning disable CS1591
        Vtt,
        #pragma warning restore CS1591
    }
}
