// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    /// <summary>The OCR engine to use. String. Allowed values: auto, easyocr, ocrmac, rapidocr, tesserocr, tesseract. Optional, defaults to easyocr.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Ocr_engines_enum
    {
        [EnumMember(Value = "auto")]
        #pragma warning disable CS1591
        Auto,
        #pragma warning restore CS1591
        [EnumMember(Value = "easyocr")]
        #pragma warning disable CS1591
        Easyocr,
        #pragma warning restore CS1591
        [EnumMember(Value = "ocrmac")]
        #pragma warning disable CS1591
        Ocrmac,
        #pragma warning restore CS1591
        [EnumMember(Value = "rapidocr")]
        #pragma warning disable CS1591
        Rapidocr,
        #pragma warning restore CS1591
        [EnumMember(Value = "tesserocr")]
        #pragma warning disable CS1591
        Tesserocr,
        #pragma warning restore CS1591
        [EnumMember(Value = "tesseract")]
        #pragma warning disable CS1591
        Tesseract,
        #pragma warning restore CS1591
    }
}
