// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum OutputFormat
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "md")]
        #pragma warning disable CS1591
        Md,
        #pragma warning restore CS1591
        [EnumMember(Value = "json")]
        #pragma warning disable CS1591
        Json,
        #pragma warning restore CS1591
        [EnumMember(Value = "html")]
        #pragma warning disable CS1591
        Html,
        #pragma warning restore CS1591
        [EnumMember(Value = "html_split_page")]
        #pragma warning disable CS1591
        Html_split_page,
        #pragma warning restore CS1591
        [EnumMember(Value = "text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
        [EnumMember(Value = "doctags")]
        #pragma warning disable CS1591
        Doctags,
        #pragma warning restore CS1591
    }
}
