// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    /// <summary>The PDF backend to use. String. Allowed values: pypdfium2, dlparse_v1, dlparse_v2, dlparse_v4. Optional, defaults to dlparse_v4.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PdfBackend
    {
        [EnumMember(Value = "pypdfium2")]
        #pragma warning disable CS1591
        Pypdfium2,
        #pragma warning restore CS1591
        [EnumMember(Value = "dlparse_v1")]
        #pragma warning disable CS1591
        Dlparse_v1,
        #pragma warning restore CS1591
        [EnumMember(Value = "dlparse_v2")]
        #pragma warning disable CS1591
        Dlparse_v2,
        #pragma warning restore CS1591
        [EnumMember(Value = "dlparse_v4")]
        #pragma warning disable CS1591
        Dlparse_v4,
        #pragma warning restore CS1591
    }
}
