// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DoclingServe.Models
{
    /// <summary>
    /// PictureMoleculeData.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PictureMoleculeData : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The class_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClassName { get; set; }
#nullable restore
#else
        public string ClassName { get; set; }
#endif
        /// <summary>The confidence property</summary>
        public double? Confidence { get; set; }
        /// <summary>The kind property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Kind { get; set; }
#nullable restore
#else
        public string Kind { get; set; }
#endif
        /// <summary>The provenance property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Provenance { get; set; }
#nullable restore
#else
        public string Provenance { get; set; }
#endif
        /// <summary>The segmentation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<UntypedNode>? Segmentation { get; set; }
#nullable restore
#else
        public List<UntypedNode> Segmentation { get; set; }
#endif
        /// <summary>The smi property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Smi { get; set; }
#nullable restore
#else
        public string Smi { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.Models.PictureMoleculeData"/> and sets the default values.
        /// </summary>
        public PictureMoleculeData()
        {
            AdditionalData = new Dictionary<string, object>();
            Kind = "molecule_data";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DoclingServe.Models.PictureMoleculeData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DoclingServe.Models.PictureMoleculeData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DoclingServe.Models.PictureMoleculeData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "class_name", n => { ClassName = n.GetStringValue(); } },
                { "confidence", n => { Confidence = n.GetDoubleValue(); } },
                { "kind", n => { Kind = n.GetStringValue(); } },
                { "provenance", n => { Provenance = n.GetStringValue(); } },
                { "segmentation", n => { Segmentation = n.GetCollectionOfPrimitiveValues<UntypedNode>()?.AsList(); } },
                { "smi", n => { Smi = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("class_name", ClassName);
            writer.WriteDoubleValue("confidence", Confidence);
            writer.WriteStringValue("kind", Kind);
            writer.WriteStringValue("provenance", Provenance);
            writer.WriteCollectionOfPrimitiveValues<UntypedNode>("segmentation", Segmentation);
            writer.WriteStringValue("smi", Smi);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
