// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DoclingServe.Models
{
    /// <summary>
    /// Represents data of a line chart.Attributes:    kind (Literal[&quot;line_chart_data&quot;]): The type of the chart.    x_axis_label (str): The label for the x-axis.    y_axis_label (str): The label for the y-axis.    lines (List[ChartLine]): A list of lines in the chart.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PictureLineChartData : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The kind property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Kind { get; set; }
#nullable restore
#else
        public string Kind { get; set; }
#endif
        /// <summary>The lines property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DoclingServe.Models.ChartLine>? Lines { get; set; }
#nullable restore
#else
        public List<global::DoclingServe.Models.ChartLine> Lines { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The x_axis_label property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? XAxisLabel { get; set; }
#nullable restore
#else
        public string XAxisLabel { get; set; }
#endif
        /// <summary>The y_axis_label property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? YAxisLabel { get; set; }
#nullable restore
#else
        public string YAxisLabel { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.Models.PictureLineChartData"/> and sets the default values.
        /// </summary>
        public PictureLineChartData()
        {
            AdditionalData = new Dictionary<string, object>();
            Kind = "line_chart_data";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DoclingServe.Models.PictureLineChartData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DoclingServe.Models.PictureLineChartData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DoclingServe.Models.PictureLineChartData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "kind", n => { Kind = n.GetStringValue(); } },
                { "lines", n => { Lines = n.GetCollectionOfObjectValues<global::DoclingServe.Models.ChartLine>(global::DoclingServe.Models.ChartLine.CreateFromDiscriminatorValue)?.AsList(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "x_axis_label", n => { XAxisLabel = n.GetStringValue(); } },
                { "y_axis_label", n => { YAxisLabel = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("kind", Kind);
            writer.WriteCollectionOfObjectValues<global::DoclingServe.Models.ChartLine>("lines", Lines);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("x_axis_label", XAxisLabel);
            writer.WriteStringValue("y_axis_label", YAxisLabel);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
