// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DoclingServe.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PictureDescriptionLocal : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Config from https://huggingface.co/docs/transformers/en/main_classes/text_generation#transformers.GenerationConfig</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.PictureDescriptionLocal_generation_config? GenerationConfig { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.PictureDescriptionLocal_generation_config GenerationConfig { get; set; }
#endif
        /// <summary>Prompt used when calling the vision-language model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prompt { get; set; }
#nullable restore
#else
        public string Prompt { get; set; }
#endif
        /// <summary>Repository id from the Hugging Face Hub.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RepoId { get; set; }
#nullable restore
#else
        public string RepoId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.Models.PictureDescriptionLocal"/> and sets the default values.
        /// </summary>
        public PictureDescriptionLocal()
        {
            AdditionalData = new Dictionary<string, object>();
            Prompt = "Describe this image in a few sentences.";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DoclingServe.Models.PictureDescriptionLocal"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DoclingServe.Models.PictureDescriptionLocal CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DoclingServe.Models.PictureDescriptionLocal();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "generation_config", n => { GenerationConfig = n.GetObjectValue<global::DoclingServe.Models.PictureDescriptionLocal_generation_config>(global::DoclingServe.Models.PictureDescriptionLocal_generation_config.CreateFromDiscriminatorValue); } },
                { "prompt", n => { Prompt = n.GetStringValue(); } },
                { "repo_id", n => { RepoId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::DoclingServe.Models.PictureDescriptionLocal_generation_config>("generation_config", GenerationConfig);
            writer.WriteStringValue("prompt", Prompt);
            writer.WriteStringValue("repo_id", RepoId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
