// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DoclingServe.Models
{
    /// <summary>
    /// PictureItem.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PictureItem : IParsable
    {
        /// <summary>The annotations property</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DoclingServe.Models.PictureItem.PictureItem_annotations>? Annotations { get; set; }
#nullable restore
#else
        public List<global::DoclingServe.Models.PictureItem.PictureItem_annotations> Annotations { get; set; }
#endif
        /// <summary>The captions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DoclingServe.Models.RefItem>? Captions { get; set; }
#nullable restore
#else
        public List<global::DoclingServe.Models.RefItem> Captions { get; set; }
#endif
        /// <summary>The children property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DoclingServe.Models.RefItem>? Children { get; set; }
#nullable restore
#else
        public List<global::DoclingServe.Models.RefItem> Children { get; set; }
#endif
        /// <summary>ContentLayer.</summary>
        public global::DoclingServe.Models.ContentLayer? ContentLayer { get; set; }
        /// <summary>The footnotes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DoclingServe.Models.RefItem>? Footnotes { get; set; }
#nullable restore
#else
        public List<global::DoclingServe.Models.RefItem> Footnotes { get; set; }
#endif
        /// <summary>The image property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.ImageRef? Image { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.ImageRef Image { get; set; }
#endif
        /// <summary>The label property</summary>
        public global::DoclingServe.Models.PictureItem_label? Label { get; set; }
        /// <summary>The meta property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.PictureMeta? Meta { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.PictureMeta Meta { get; set; }
#endif
        /// <summary>The parent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.RefItem? Parent { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.RefItem Parent { get; set; }
#endif
        /// <summary>The prov property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DoclingServe.Models.ProvenanceItem>? Prov { get; set; }
#nullable restore
#else
        public List<global::DoclingServe.Models.ProvenanceItem> Prov { get; set; }
#endif
        /// <summary>The references property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DoclingServe.Models.RefItem>? References { get; set; }
#nullable restore
#else
        public List<global::DoclingServe.Models.RefItem> References { get; set; }
#endif
        /// <summary>The self_ref property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SelfRef { get; set; }
#nullable restore
#else
        public string SelfRef { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.Models.PictureItem"/> and sets the default values.
        /// </summary>
        public PictureItem()
        {
            ContentLayer = global::DoclingServe.Models.ContentLayer.Body;
            Label = global::DoclingServe.Models.PictureItem_label.Picture;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DoclingServe.Models.PictureItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DoclingServe.Models.PictureItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DoclingServe.Models.PictureItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "annotations", n => { Annotations = n.GetCollectionOfObjectValues<global::DoclingServe.Models.PictureItem.PictureItem_annotations>(global::DoclingServe.Models.PictureItem.PictureItem_annotations.CreateFromDiscriminatorValue)?.AsList(); } },
                { "captions", n => { Captions = n.GetCollectionOfObjectValues<global::DoclingServe.Models.RefItem>(global::DoclingServe.Models.RefItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "children", n => { Children = n.GetCollectionOfObjectValues<global::DoclingServe.Models.RefItem>(global::DoclingServe.Models.RefItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "content_layer", n => { ContentLayer = n.GetEnumValue<global::DoclingServe.Models.ContentLayer>(); } },
                { "footnotes", n => { Footnotes = n.GetCollectionOfObjectValues<global::DoclingServe.Models.RefItem>(global::DoclingServe.Models.RefItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "image", n => { Image = n.GetObjectValue<global::DoclingServe.Models.ImageRef>(global::DoclingServe.Models.ImageRef.CreateFromDiscriminatorValue); } },
                { "label", n => { Label = n.GetEnumValue<global::DoclingServe.Models.PictureItem_label>(); } },
                { "meta", n => { Meta = n.GetObjectValue<global::DoclingServe.Models.PictureMeta>(global::DoclingServe.Models.PictureMeta.CreateFromDiscriminatorValue); } },
                { "parent", n => { Parent = n.GetObjectValue<global::DoclingServe.Models.RefItem>(global::DoclingServe.Models.RefItem.CreateFromDiscriminatorValue); } },
                { "prov", n => { Prov = n.GetCollectionOfObjectValues<global::DoclingServe.Models.ProvenanceItem>(global::DoclingServe.Models.ProvenanceItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "references", n => { References = n.GetCollectionOfObjectValues<global::DoclingServe.Models.RefItem>(global::DoclingServe.Models.RefItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "self_ref", n => { SelfRef = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::DoclingServe.Models.PictureItem.PictureItem_annotations>("annotations", Annotations);
            writer.WriteCollectionOfObjectValues<global::DoclingServe.Models.RefItem>("captions", Captions);
            writer.WriteCollectionOfObjectValues<global::DoclingServe.Models.RefItem>("children", Children);
            writer.WriteEnumValue<global::DoclingServe.Models.ContentLayer>("content_layer", ContentLayer);
            writer.WriteCollectionOfObjectValues<global::DoclingServe.Models.RefItem>("footnotes", Footnotes);
            writer.WriteObjectValue<global::DoclingServe.Models.ImageRef>("image", Image);
            writer.WriteEnumValue<global::DoclingServe.Models.PictureItem_label>("label", Label);
            writer.WriteObjectValue<global::DoclingServe.Models.PictureMeta>("meta", Meta);
            writer.WriteObjectValue<global::DoclingServe.Models.RefItem>("parent", Parent);
            writer.WriteCollectionOfObjectValues<global::DoclingServe.Models.ProvenanceItem>("prov", Prov);
            writer.WriteCollectionOfObjectValues<global::DoclingServe.Models.RefItem>("references", References);
            writer.WriteStringValue("self_ref", SelfRef);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::DoclingServe.Models.DescriptionAnnotation"/>, <see cref="global::DoclingServe.Models.MiscAnnotation"/>, <see cref="global::DoclingServe.Models.PictureBarChartData"/>, <see cref="global::DoclingServe.Models.PictureClassificationData"/>, <see cref="global::DoclingServe.Models.PictureLineChartData"/>, <see cref="global::DoclingServe.Models.PictureMoleculeData"/>, <see cref="global::DoclingServe.Models.PicturePieChartData"/>, <see cref="global::DoclingServe.Models.PictureScatterChartData"/>, <see cref="global::DoclingServe.Models.PictureStackedBarChartData"/>, <see cref="global::DoclingServe.Models.PictureTabularChartData"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PictureItem_annotations : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.DescriptionAnnotation"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.DescriptionAnnotation? DescriptionAnnotation { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.DescriptionAnnotation DescriptionAnnotation { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.MiscAnnotation"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.MiscAnnotation? MiscAnnotation { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.MiscAnnotation MiscAnnotation { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.PictureBarChartData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.PictureBarChartData? PictureBarChartData { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.PictureBarChartData PictureBarChartData { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.PictureClassificationData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.PictureClassificationData? PictureClassificationData { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.PictureClassificationData PictureClassificationData { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.PictureLineChartData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.PictureLineChartData? PictureLineChartData { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.PictureLineChartData PictureLineChartData { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.PictureMoleculeData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.PictureMoleculeData? PictureMoleculeData { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.PictureMoleculeData PictureMoleculeData { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.PicturePieChartData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.PicturePieChartData? PicturePieChartData { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.PicturePieChartData PicturePieChartData { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.PictureScatterChartData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.PictureScatterChartData? PictureScatterChartData { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.PictureScatterChartData PictureScatterChartData { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.PictureStackedBarChartData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.PictureStackedBarChartData? PictureStackedBarChartData { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.PictureStackedBarChartData PictureStackedBarChartData { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.PictureTabularChartData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.PictureTabularChartData? PictureTabularChartData { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.PictureTabularChartData PictureTabularChartData { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::DoclingServe.Models.PictureItem.PictureItem_annotations"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::DoclingServe.Models.PictureItem.PictureItem_annotations CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("kind")?.GetStringValue();
                var result = new global::DoclingServe.Models.PictureItem.PictureItem_annotations();
                if("description".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.DescriptionAnnotation = new global::DoclingServe.Models.DescriptionAnnotation();
                }
                else if("misc".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.MiscAnnotation = new global::DoclingServe.Models.MiscAnnotation();
                }
                else if("bar_chart_data".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PictureBarChartData = new global::DoclingServe.Models.PictureBarChartData();
                }
                else if("classification".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PictureClassificationData = new global::DoclingServe.Models.PictureClassificationData();
                }
                else if("line_chart_data".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PictureLineChartData = new global::DoclingServe.Models.PictureLineChartData();
                }
                else if("molecule_data".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PictureMoleculeData = new global::DoclingServe.Models.PictureMoleculeData();
                }
                else if("pie_chart_data".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PicturePieChartData = new global::DoclingServe.Models.PicturePieChartData();
                }
                else if("scatter_chart_data".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PictureScatterChartData = new global::DoclingServe.Models.PictureScatterChartData();
                }
                else if("stacked_bar_chart_data".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PictureStackedBarChartData = new global::DoclingServe.Models.PictureStackedBarChartData();
                }
                else if("tabular_chart_data".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PictureTabularChartData = new global::DoclingServe.Models.PictureTabularChartData();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(DescriptionAnnotation != null)
                {
                    return DescriptionAnnotation.GetFieldDeserializers();
                }
                else if(MiscAnnotation != null)
                {
                    return MiscAnnotation.GetFieldDeserializers();
                }
                else if(PictureBarChartData != null)
                {
                    return PictureBarChartData.GetFieldDeserializers();
                }
                else if(PictureClassificationData != null)
                {
                    return PictureClassificationData.GetFieldDeserializers();
                }
                else if(PictureLineChartData != null)
                {
                    return PictureLineChartData.GetFieldDeserializers();
                }
                else if(PictureMoleculeData != null)
                {
                    return PictureMoleculeData.GetFieldDeserializers();
                }
                else if(PicturePieChartData != null)
                {
                    return PicturePieChartData.GetFieldDeserializers();
                }
                else if(PictureScatterChartData != null)
                {
                    return PictureScatterChartData.GetFieldDeserializers();
                }
                else if(PictureStackedBarChartData != null)
                {
                    return PictureStackedBarChartData.GetFieldDeserializers();
                }
                else if(PictureTabularChartData != null)
                {
                    return PictureTabularChartData.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(DescriptionAnnotation != null)
                {
                    writer.WriteObjectValue<global::DoclingServe.Models.DescriptionAnnotation>(null, DescriptionAnnotation);
                }
                else if(MiscAnnotation != null)
                {
                    writer.WriteObjectValue<global::DoclingServe.Models.MiscAnnotation>(null, MiscAnnotation);
                }
                else if(PictureBarChartData != null)
                {
                    writer.WriteObjectValue<global::DoclingServe.Models.PictureBarChartData>(null, PictureBarChartData);
                }
                else if(PictureClassificationData != null)
                {
                    writer.WriteObjectValue<global::DoclingServe.Models.PictureClassificationData>(null, PictureClassificationData);
                }
                else if(PictureLineChartData != null)
                {
                    writer.WriteObjectValue<global::DoclingServe.Models.PictureLineChartData>(null, PictureLineChartData);
                }
                else if(PictureMoleculeData != null)
                {
                    writer.WriteObjectValue<global::DoclingServe.Models.PictureMoleculeData>(null, PictureMoleculeData);
                }
                else if(PicturePieChartData != null)
                {
                    writer.WriteObjectValue<global::DoclingServe.Models.PicturePieChartData>(null, PicturePieChartData);
                }
                else if(PictureScatterChartData != null)
                {
                    writer.WriteObjectValue<global::DoclingServe.Models.PictureScatterChartData>(null, PictureScatterChartData);
                }
                else if(PictureStackedBarChartData != null)
                {
                    writer.WriteObjectValue<global::DoclingServe.Models.PictureStackedBarChartData>(null, PictureStackedBarChartData);
                }
                else if(PictureTabularChartData != null)
                {
                    writer.WriteObjectValue<global::DoclingServe.Models.PictureTabularChartData>(null, PictureTabularChartData);
                }
            }
        }
    }
}
#pragma warning restore CS0618
