// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DoclingServe.Models
{
    /// <summary>
    /// Metadata model for pictures.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PictureMeta : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The classification property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.PictureClassificationMetaField? Classification { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.PictureClassificationMetaField Classification { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.DescriptionMetaField? Description { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.DescriptionMetaField Description { get; set; }
#endif
        /// <summary>The molecule property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.MoleculeMetaField? Molecule { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.MoleculeMetaField Molecule { get; set; }
#endif
        /// <summary>The summary property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.SummaryMetaField? Summary { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.SummaryMetaField Summary { get; set; }
#endif
        /// <summary>The tabular_chart property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.TabularChartMetaField? TabularChart { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.TabularChartMetaField TabularChart { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.Models.PictureMeta"/> and sets the default values.
        /// </summary>
        public PictureMeta()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DoclingServe.Models.PictureMeta"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DoclingServe.Models.PictureMeta CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DoclingServe.Models.PictureMeta();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "classification", n => { Classification = n.GetObjectValue<global::DoclingServe.Models.PictureClassificationMetaField>(global::DoclingServe.Models.PictureClassificationMetaField.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetObjectValue<global::DoclingServe.Models.DescriptionMetaField>(global::DoclingServe.Models.DescriptionMetaField.CreateFromDiscriminatorValue); } },
                { "molecule", n => { Molecule = n.GetObjectValue<global::DoclingServe.Models.MoleculeMetaField>(global::DoclingServe.Models.MoleculeMetaField.CreateFromDiscriminatorValue); } },
                { "summary", n => { Summary = n.GetObjectValue<global::DoclingServe.Models.SummaryMetaField>(global::DoclingServe.Models.SummaryMetaField.CreateFromDiscriminatorValue); } },
                { "tabular_chart", n => { TabularChart = n.GetObjectValue<global::DoclingServe.Models.TabularChartMetaField>(global::DoclingServe.Models.TabularChartMetaField.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::DoclingServe.Models.PictureClassificationMetaField>("classification", Classification);
            writer.WriteObjectValue<global::DoclingServe.Models.DescriptionMetaField>("description", Description);
            writer.WriteObjectValue<global::DoclingServe.Models.MoleculeMetaField>("molecule", Molecule);
            writer.WriteObjectValue<global::DoclingServe.Models.SummaryMetaField>("summary", Summary);
            writer.WriteObjectValue<global::DoclingServe.Models.TabularChartMetaField>("tabular_chart", TabularChart);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
