// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PictureItem_label
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "picture")]
        #pragma warning disable CS1591
        Picture,
        #pragma warning restore CS1591
        [EnumMember(Value = "chart")]
        #pragma warning disable CS1591
        Chart,
        #pragma warning restore CS1591
    }
}
