// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    /// <summary>Choose the pipeline to process PDF or image files.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProcessingPipeline
    {
        [EnumMember(Value = "legacy")]
        #pragma warning disable CS1591
        Legacy,
        #pragma warning restore CS1591
        [EnumMember(Value = "standard")]
        #pragma warning disable CS1591
        Standard,
        #pragma warning restore CS1591
        [EnumMember(Value = "vlm")]
        #pragma warning disable CS1591
        Vlm,
        #pragma warning restore CS1591
        [EnumMember(Value = "asr")]
        #pragma warning disable CS1591
        Asr,
        #pragma warning restore CS1591
    }
}
