// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    /// <summary>Type of response generated by the model.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ResponseFormat
    {
        [EnumMember(Value = "doctags")]
        #pragma warning disable CS1591
        Doctags,
        #pragma warning restore CS1591
        [EnumMember(Value = "markdown")]
        #pragma warning disable CS1591
        Markdown,
        #pragma warning restore CS1591
        [EnumMember(Value = "html")]
        #pragma warning disable CS1591
        Html,
        #pragma warning restore CS1591
        [EnumMember(Value = "otsl")]
        #pragma warning disable CS1591
        Otsl,
        #pragma warning restore CS1591
        [EnumMember(Value = "plaintext")]
        #pragma warning disable CS1591
        Plaintext,
        #pragma warning restore CS1591
    }
}
