// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DoclingServe.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class S3SourceRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>S3 access key. Required.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccessKey { get; set; }
#nullable restore
#else
        public string AccessKey { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>S3 bucket name. Required.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Bucket { get; set; }
#nullable restore
#else
        public string Bucket { get; set; }
#endif
        /// <summary>S3 service endpoint, without protocol. Required.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Endpoint { get; set; }
#nullable restore
#else
        public string Endpoint { get; set; }
#endif
        /// <summary>Prefix for the object keys on s3. Optional, defaults to empty.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? KeyPrefix { get; set; }
#nullable restore
#else
        public string KeyPrefix { get; set; }
#endif
        /// <summary>The kind property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Kind { get; set; }
#nullable restore
#else
        public string Kind { get; set; }
#endif
        /// <summary>S3 secret key. Required.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecretKey { get; set; }
#nullable restore
#else
        public string SecretKey { get; set; }
#endif
        /// <summary>If enabled, SSL will be used to connect to s3. Boolean. Optional, defaults to true</summary>
        public bool? VerifySsl { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.Models.S3SourceRequest"/> and sets the default values.
        /// </summary>
        public S3SourceRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            Kind = "s3";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DoclingServe.Models.S3SourceRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DoclingServe.Models.S3SourceRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DoclingServe.Models.S3SourceRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "access_key", n => { AccessKey = n.GetStringValue(); } },
                { "bucket", n => { Bucket = n.GetStringValue(); } },
                { "endpoint", n => { Endpoint = n.GetStringValue(); } },
                { "key_prefix", n => { KeyPrefix = n.GetStringValue(); } },
                { "kind", n => { Kind = n.GetStringValue(); } },
                { "secret_key", n => { SecretKey = n.GetStringValue(); } },
                { "verify_ssl", n => { VerifySsl = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("access_key", AccessKey);
            writer.WriteStringValue("bucket", Bucket);
            writer.WriteStringValue("endpoint", Endpoint);
            writer.WriteStringValue("key_prefix", KeyPrefix);
            writer.WriteStringValue("kind", Kind);
            writer.WriteStringValue("secret_key", SecretKey);
            writer.WriteBoolValue("verify_ssl", VerifySsl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
