// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    /// <summary>Text script position.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Script
    {
        [EnumMember(Value = "baseline")]
        #pragma warning disable CS1591
        Baseline,
        #pragma warning restore CS1591
        [EnumMember(Value = "sub")]
        #pragma warning disable CS1591
        Sub,
        #pragma warning restore CS1591
        [EnumMember(Value = "super")]
        #pragma warning disable CS1591
        Super,
        #pragma warning restore CS1591
    }
}
