// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TableItem_label
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "document_index")]
        #pragma warning disable CS1591
        Document_index,
        #pragma warning restore CS1591
        [EnumMember(Value = "table")]
        #pragma warning disable CS1591
        Table,
        #pragma warning restore CS1591
    }
}
