// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DoclingServe.Models
{
    /// <summary>
    /// TableItem.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TableItem : IParsable
    {
        /// <summary>The annotations property</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DoclingServe.Models.TableItem.TableItem_annotations>? Annotations { get; set; }
#nullable restore
#else
        public List<global::DoclingServe.Models.TableItem.TableItem_annotations> Annotations { get; set; }
#endif
        /// <summary>The captions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DoclingServe.Models.RefItem>? Captions { get; set; }
#nullable restore
#else
        public List<global::DoclingServe.Models.RefItem> Captions { get; set; }
#endif
        /// <summary>The children property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DoclingServe.Models.RefItem>? Children { get; set; }
#nullable restore
#else
        public List<global::DoclingServe.Models.RefItem> Children { get; set; }
#endif
        /// <summary>ContentLayer.</summary>
        public global::DoclingServe.Models.ContentLayer? ContentLayer { get; set; }
        /// <summary>BaseTableData.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.TableData? Data { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.TableData Data { get; set; }
#endif
        /// <summary>The footnotes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DoclingServe.Models.RefItem>? Footnotes { get; set; }
#nullable restore
#else
        public List<global::DoclingServe.Models.RefItem> Footnotes { get; set; }
#endif
        /// <summary>The image property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.ImageRef? Image { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.ImageRef Image { get; set; }
#endif
        /// <summary>The label property</summary>
        public global::DoclingServe.Models.TableItem_label? Label { get; set; }
        /// <summary>The meta property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.FloatingMeta? Meta { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.FloatingMeta Meta { get; set; }
#endif
        /// <summary>The parent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.RefItem? Parent { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.RefItem Parent { get; set; }
#endif
        /// <summary>The prov property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DoclingServe.Models.ProvenanceItem>? Prov { get; set; }
#nullable restore
#else
        public List<global::DoclingServe.Models.ProvenanceItem> Prov { get; set; }
#endif
        /// <summary>The references property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DoclingServe.Models.RefItem>? References { get; set; }
#nullable restore
#else
        public List<global::DoclingServe.Models.RefItem> References { get; set; }
#endif
        /// <summary>The self_ref property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SelfRef { get; set; }
#nullable restore
#else
        public string SelfRef { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.Models.TableItem"/> and sets the default values.
        /// </summary>
        public TableItem()
        {
            ContentLayer = global::DoclingServe.Models.ContentLayer.Body;
            Label = global::DoclingServe.Models.TableItem_label.Table;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DoclingServe.Models.TableItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DoclingServe.Models.TableItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DoclingServe.Models.TableItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "annotations", n => { Annotations = n.GetCollectionOfObjectValues<global::DoclingServe.Models.TableItem.TableItem_annotations>(global::DoclingServe.Models.TableItem.TableItem_annotations.CreateFromDiscriminatorValue)?.AsList(); } },
                { "captions", n => { Captions = n.GetCollectionOfObjectValues<global::DoclingServe.Models.RefItem>(global::DoclingServe.Models.RefItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "children", n => { Children = n.GetCollectionOfObjectValues<global::DoclingServe.Models.RefItem>(global::DoclingServe.Models.RefItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "content_layer", n => { ContentLayer = n.GetEnumValue<global::DoclingServe.Models.ContentLayer>(); } },
                { "data", n => { Data = n.GetObjectValue<global::DoclingServe.Models.TableData>(global::DoclingServe.Models.TableData.CreateFromDiscriminatorValue); } },
                { "footnotes", n => { Footnotes = n.GetCollectionOfObjectValues<global::DoclingServe.Models.RefItem>(global::DoclingServe.Models.RefItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "image", n => { Image = n.GetObjectValue<global::DoclingServe.Models.ImageRef>(global::DoclingServe.Models.ImageRef.CreateFromDiscriminatorValue); } },
                { "label", n => { Label = n.GetEnumValue<global::DoclingServe.Models.TableItem_label>(); } },
                { "meta", n => { Meta = n.GetObjectValue<global::DoclingServe.Models.FloatingMeta>(global::DoclingServe.Models.FloatingMeta.CreateFromDiscriminatorValue); } },
                { "parent", n => { Parent = n.GetObjectValue<global::DoclingServe.Models.RefItem>(global::DoclingServe.Models.RefItem.CreateFromDiscriminatorValue); } },
                { "prov", n => { Prov = n.GetCollectionOfObjectValues<global::DoclingServe.Models.ProvenanceItem>(global::DoclingServe.Models.ProvenanceItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "references", n => { References = n.GetCollectionOfObjectValues<global::DoclingServe.Models.RefItem>(global::DoclingServe.Models.RefItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "self_ref", n => { SelfRef = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::DoclingServe.Models.TableItem.TableItem_annotations>("annotations", Annotations);
            writer.WriteCollectionOfObjectValues<global::DoclingServe.Models.RefItem>("captions", Captions);
            writer.WriteCollectionOfObjectValues<global::DoclingServe.Models.RefItem>("children", Children);
            writer.WriteEnumValue<global::DoclingServe.Models.ContentLayer>("content_layer", ContentLayer);
            writer.WriteObjectValue<global::DoclingServe.Models.TableData>("data", Data);
            writer.WriteCollectionOfObjectValues<global::DoclingServe.Models.RefItem>("footnotes", Footnotes);
            writer.WriteObjectValue<global::DoclingServe.Models.ImageRef>("image", Image);
            writer.WriteEnumValue<global::DoclingServe.Models.TableItem_label>("label", Label);
            writer.WriteObjectValue<global::DoclingServe.Models.FloatingMeta>("meta", Meta);
            writer.WriteObjectValue<global::DoclingServe.Models.RefItem>("parent", Parent);
            writer.WriteCollectionOfObjectValues<global::DoclingServe.Models.ProvenanceItem>("prov", Prov);
            writer.WriteCollectionOfObjectValues<global::DoclingServe.Models.RefItem>("references", References);
            writer.WriteStringValue("self_ref", SelfRef);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::DoclingServe.Models.DescriptionAnnotation"/>, <see cref="global::DoclingServe.Models.MiscAnnotation"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TableItem_annotations : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.DescriptionAnnotation"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.DescriptionAnnotation? DescriptionAnnotation { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.DescriptionAnnotation DescriptionAnnotation { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.MiscAnnotation"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.MiscAnnotation? MiscAnnotation { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.MiscAnnotation MiscAnnotation { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::DoclingServe.Models.TableItem.TableItem_annotations"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::DoclingServe.Models.TableItem.TableItem_annotations CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("kind")?.GetStringValue();
                var result = new global::DoclingServe.Models.TableItem.TableItem_annotations();
                if("description".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.DescriptionAnnotation = new global::DoclingServe.Models.DescriptionAnnotation();
                }
                else if("misc".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.MiscAnnotation = new global::DoclingServe.Models.MiscAnnotation();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(DescriptionAnnotation != null)
                {
                    return DescriptionAnnotation.GetFieldDeserializers();
                }
                else if(MiscAnnotation != null)
                {
                    return MiscAnnotation.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(DescriptionAnnotation != null)
                {
                    writer.WriteObjectValue<global::DoclingServe.Models.DescriptionAnnotation>(null, DescriptionAnnotation);
                }
                else if(MiscAnnotation != null)
                {
                    writer.WriteObjectValue<global::DoclingServe.Models.MiscAnnotation>(null, MiscAnnotation);
                }
            }
        }
    }
}
#pragma warning restore CS0618
