// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DoclingServe.Models
{
    /// <summary>
    /// TableCell.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TableCell : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bbox property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.BoundingBox? Bbox { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.BoundingBox Bbox { get; set; }
#endif
        /// <summary>The col_span property</summary>
        public int? ColSpan { get; set; }
        /// <summary>The column_header property</summary>
        public bool? ColumnHeader { get; set; }
        /// <summary>The end_col_offset_idx property</summary>
        public int? EndColOffsetIdx { get; set; }
        /// <summary>The end_row_offset_idx property</summary>
        public int? EndRowOffsetIdx { get; set; }
        /// <summary>The fillable property</summary>
        public bool? Fillable { get; set; }
        /// <summary>The row_header property</summary>
        public bool? RowHeader { get; set; }
        /// <summary>The row_section property</summary>
        public bool? RowSection { get; set; }
        /// <summary>The row_span property</summary>
        public int? RowSpan { get; set; }
        /// <summary>The start_col_offset_idx property</summary>
        public int? StartColOffsetIdx { get; set; }
        /// <summary>The start_row_offset_idx property</summary>
        public int? StartRowOffsetIdx { get; set; }
        /// <summary>The text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.Models.TableCell"/> and sets the default values.
        /// </summary>
        public TableCell()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DoclingServe.Models.TableCell"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DoclingServe.Models.TableCell CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DoclingServe.Models.TableCell();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bbox", n => { Bbox = n.GetObjectValue<global::DoclingServe.Models.BoundingBox>(global::DoclingServe.Models.BoundingBox.CreateFromDiscriminatorValue); } },
                { "col_span", n => { ColSpan = n.GetIntValue(); } },
                { "column_header", n => { ColumnHeader = n.GetBoolValue(); } },
                { "end_col_offset_idx", n => { EndColOffsetIdx = n.GetIntValue(); } },
                { "end_row_offset_idx", n => { EndRowOffsetIdx = n.GetIntValue(); } },
                { "fillable", n => { Fillable = n.GetBoolValue(); } },
                { "row_header", n => { RowHeader = n.GetBoolValue(); } },
                { "row_section", n => { RowSection = n.GetBoolValue(); } },
                { "row_span", n => { RowSpan = n.GetIntValue(); } },
                { "start_col_offset_idx", n => { StartColOffsetIdx = n.GetIntValue(); } },
                { "start_row_offset_idx", n => { StartRowOffsetIdx = n.GetIntValue(); } },
                { "text", n => { Text = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::DoclingServe.Models.BoundingBox>("bbox", Bbox);
            writer.WriteIntValue("col_span", ColSpan);
            writer.WriteBoolValue("column_header", ColumnHeader);
            writer.WriteIntValue("end_col_offset_idx", EndColOffsetIdx);
            writer.WriteIntValue("end_row_offset_idx", EndRowOffsetIdx);
            writer.WriteBoolValue("fillable", Fillable);
            writer.WriteBoolValue("row_header", RowHeader);
            writer.WriteBoolValue("row_section", RowSection);
            writer.WriteIntValue("row_span", RowSpan);
            writer.WriteIntValue("start_col_offset_idx", StartColOffsetIdx);
            writer.WriteIntValue("start_row_offset_idx", StartRowOffsetIdx);
            writer.WriteStringValue("text", Text);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
