// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    /// <summary>Mode to use for table structure, String. Allowed values: fast, accurate. Optional, defaults to accurate.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TableFormerMode
    {
        [EnumMember(Value = "fast")]
        #pragma warning disable CS1591
        Fast,
        #pragma warning restore CS1591
        [EnumMember(Value = "accurate")]
        #pragma warning disable CS1591
        Accurate,
        #pragma warning restore CS1591
    }
}
