// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DoclingServe.Models
{
    /// <summary>
    /// BaseTableData.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TableData : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>grid.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Grid { get; private set; }
#nullable restore
#else
        public UntypedNode Grid { get; private set; }
#endif
        /// <summary>The num_cols property</summary>
        public int? NumCols { get; set; }
        /// <summary>The num_rows property</summary>
        public int? NumRows { get; set; }
        /// <summary>The table_cells property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DoclingServe.Models.TableData.TableData_table_cells>? TableCells { get; set; }
#nullable restore
#else
        public List<global::DoclingServe.Models.TableData.TableData_table_cells> TableCells { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.Models.TableData"/> and sets the default values.
        /// </summary>
        public TableData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DoclingServe.Models.TableData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DoclingServe.Models.TableData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DoclingServe.Models.TableData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "grid", n => { Grid = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "num_cols", n => { NumCols = n.GetIntValue(); } },
                { "num_rows", n => { NumRows = n.GetIntValue(); } },
                { "table_cells", n => { TableCells = n.GetCollectionOfObjectValues<global::DoclingServe.Models.TableData.TableData_table_cells>(global::DoclingServe.Models.TableData.TableData_table_cells.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("num_cols", NumCols);
            writer.WriteIntValue("num_rows", NumRows);
            writer.WriteCollectionOfObjectValues<global::DoclingServe.Models.TableData.TableData_table_cells>("table_cells", TableCells);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::DoclingServe.Models.RichTableCell"/>, <see cref="global::DoclingServe.Models.TableCell"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TableData_table_cells : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.RichTableCell"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.RichTableCell? RichTableCell { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.RichTableCell RichTableCell { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.TableCell"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.TableCell? TableCell { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.TableCell TableCell { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::DoclingServe.Models.TableData.TableData_table_cells"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::DoclingServe.Models.TableData.TableData_table_cells CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::DoclingServe.Models.TableData.TableData_table_cells();
                result.RichTableCell = new global::DoclingServe.Models.RichTableCell();
                result.TableCell = new global::DoclingServe.Models.TableCell();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(RichTableCell != null || TableCell != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(RichTableCell, TableCell);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::DoclingServe.Models.RichTableCell>(null, RichTableCell, TableCell);
            }
        }
    }
}
#pragma warning restore CS0618
