// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DoclingServe.Models
{
    /// <summary>
    /// Tabular chart metadata field.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TabularChartMetaField : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>BaseTableData.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.TableData? ChartData { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.TableData ChartData { get; set; }
#endif
        /// <summary>The confidence of the prediction.</summary>
        public double? Confidence { get; set; }
        /// <summary>The origin of the prediction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.TabularChartMetaField.TabularChartMetaField_created_by? CreatedBy { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.TabularChartMetaField.TabularChartMetaField_created_by CreatedBy { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.TabularChartMetaField.TabularChartMetaField_title? Title { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.TabularChartMetaField.TabularChartMetaField_title Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.Models.TabularChartMetaField"/> and sets the default values.
        /// </summary>
        public TabularChartMetaField()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DoclingServe.Models.TabularChartMetaField"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DoclingServe.Models.TabularChartMetaField CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DoclingServe.Models.TabularChartMetaField();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "chart_data", n => { ChartData = n.GetObjectValue<global::DoclingServe.Models.TableData>(global::DoclingServe.Models.TableData.CreateFromDiscriminatorValue); } },
                { "confidence", n => { Confidence = n.GetDoubleValue(); } },
                { "created_by", n => { CreatedBy = n.GetObjectValue<global::DoclingServe.Models.TabularChartMetaField.TabularChartMetaField_created_by>(global::DoclingServe.Models.TabularChartMetaField.TabularChartMetaField_created_by.CreateFromDiscriminatorValue); } },
                { "title", n => { Title = n.GetObjectValue<global::DoclingServe.Models.TabularChartMetaField.TabularChartMetaField_title>(global::DoclingServe.Models.TabularChartMetaField.TabularChartMetaField_title.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::DoclingServe.Models.TableData>("chart_data", ChartData);
            writer.WriteDoubleValue("confidence", Confidence);
            writer.WriteObjectValue<global::DoclingServe.Models.TabularChartMetaField.TabularChartMetaField_created_by>("created_by", CreatedBy);
            writer.WriteObjectValue<global::DoclingServe.Models.TabularChartMetaField.TabularChartMetaField_title>("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::DoclingServe.Models.TabularChartMetaField_created_byMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TabularChartMetaField_created_by : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.TabularChartMetaField_created_byMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.TabularChartMetaField_created_byMember1? TabularChartMetaFieldCreatedByMember1 { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.TabularChartMetaField_created_byMember1 TabularChartMetaFieldCreatedByMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::DoclingServe.Models.TabularChartMetaField.TabularChartMetaField_created_by"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::DoclingServe.Models.TabularChartMetaField.TabularChartMetaField_created_by CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::DoclingServe.Models.TabularChartMetaField.TabularChartMetaField_created_by();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.TabularChartMetaFieldCreatedByMember1 = new global::DoclingServe.Models.TabularChartMetaField_created_byMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(TabularChartMetaFieldCreatedByMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(TabularChartMetaFieldCreatedByMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::DoclingServe.Models.TabularChartMetaField_created_byMember1>(null, TabularChartMetaFieldCreatedByMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::DoclingServe.Models.TabularChartMetaField_titleMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TabularChartMetaField_title : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.TabularChartMetaField_titleMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.TabularChartMetaField_titleMember1? TabularChartMetaFieldTitleMember1 { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.TabularChartMetaField_titleMember1 TabularChartMetaFieldTitleMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::DoclingServe.Models.TabularChartMetaField.TabularChartMetaField_title"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::DoclingServe.Models.TabularChartMetaField.TabularChartMetaField_title CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::DoclingServe.Models.TabularChartMetaField.TabularChartMetaField_title();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.TabularChartMetaFieldTitleMember1 = new global::DoclingServe.Models.TabularChartMetaField_titleMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(TabularChartMetaFieldTitleMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(TabularChartMetaFieldTitleMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::DoclingServe.Models.TabularChartMetaField_titleMember1>(null, TabularChartMetaFieldTitleMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
