// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    /// <summary>Specification for the type of output target.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TargetName
    {
        [EnumMember(Value = "inbody")]
        #pragma warning disable CS1591
        Inbody,
        #pragma warning restore CS1591
        [EnumMember(Value = "zip")]
        #pragma warning disable CS1591
        Zip,
        #pragma warning restore CS1591
    }
}
