// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DoclingServe.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TaskStatusResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The task_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaskId { get; set; }
#nullable restore
#else
        public string TaskId { get; set; }
#endif
        /// <summary>The task_meta property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.TaskProcessingMeta? TaskMeta { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.TaskProcessingMeta TaskMeta { get; set; }
#endif
        /// <summary>The task_position property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DoclingServe.Models.TaskStatusResponse.TaskStatusResponse_task_position? TaskPosition { get; set; }
#nullable restore
#else
        public global::DoclingServe.Models.TaskStatusResponse.TaskStatusResponse_task_position TaskPosition { get; set; }
#endif
        /// <summary>The task_status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaskStatus { get; set; }
#nullable restore
#else
        public string TaskStatus { get; set; }
#endif
        /// <summary>The task_type property</summary>
        public global::DoclingServe.Models.TaskType? TaskType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.Models.TaskStatusResponse"/> and sets the default values.
        /// </summary>
        public TaskStatusResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DoclingServe.Models.TaskStatusResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DoclingServe.Models.TaskStatusResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DoclingServe.Models.TaskStatusResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "task_id", n => { TaskId = n.GetStringValue(); } },
                { "task_meta", n => { TaskMeta = n.GetObjectValue<global::DoclingServe.Models.TaskProcessingMeta>(global::DoclingServe.Models.TaskProcessingMeta.CreateFromDiscriminatorValue); } },
                { "task_position", n => { TaskPosition = n.GetObjectValue<global::DoclingServe.Models.TaskStatusResponse.TaskStatusResponse_task_position>(global::DoclingServe.Models.TaskStatusResponse.TaskStatusResponse_task_position.CreateFromDiscriminatorValue); } },
                { "task_status", n => { TaskStatus = n.GetStringValue(); } },
                { "task_type", n => { TaskType = n.GetEnumValue<global::DoclingServe.Models.TaskType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("task_id", TaskId);
            writer.WriteObjectValue<global::DoclingServe.Models.TaskProcessingMeta>("task_meta", TaskMeta);
            writer.WriteObjectValue<global::DoclingServe.Models.TaskStatusResponse.TaskStatusResponse_task_position>("task_position", TaskPosition);
            writer.WriteStringValue("task_status", TaskStatus);
            writer.WriteEnumValue<global::DoclingServe.Models.TaskType>("task_type", TaskType);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::DoclingServe.Models.TaskStatusResponse_task_positionMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TaskStatusResponse_task_position : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>Composed type representation for type <see cref="global::DoclingServe.Models.TaskStatusResponse_task_positionMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DoclingServe.Models.TaskStatusResponse_task_positionMember1? TaskStatusResponseTaskPositionMember1 { get; set; }
#nullable restore
#else
            public global::DoclingServe.Models.TaskStatusResponse_task_positionMember1 TaskStatusResponseTaskPositionMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::DoclingServe.Models.TaskStatusResponse.TaskStatusResponse_task_position"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::DoclingServe.Models.TaskStatusResponse.TaskStatusResponse_task_position CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::DoclingServe.Models.TaskStatusResponse.TaskStatusResponse_task_position();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.TaskStatusResponseTaskPositionMember1 = new global::DoclingServe.Models.TaskStatusResponse_task_positionMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(TaskStatusResponseTaskPositionMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(TaskStatusResponseTaskPositionMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::DoclingServe.Models.TaskStatusResponse_task_positionMember1>(null, TaskStatusResponseTaskPositionMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
