// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TaskType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "convert")]
        #pragma warning disable CS1591
        Convert,
        #pragma warning restore CS1591
        [EnumMember(Value = "chunk")]
        #pragma warning disable CS1591
        Chunk,
        #pragma warning restore CS1591
    }
}
