// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TextItem_label
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "caption")]
        #pragma warning disable CS1591
        Caption,
        #pragma warning restore CS1591
        [EnumMember(Value = "checkbox_selected")]
        #pragma warning disable CS1591
        Checkbox_selected,
        #pragma warning restore CS1591
        [EnumMember(Value = "checkbox_unselected")]
        #pragma warning disable CS1591
        Checkbox_unselected,
        #pragma warning restore CS1591
        [EnumMember(Value = "footnote")]
        #pragma warning disable CS1591
        Footnote,
        #pragma warning restore CS1591
        [EnumMember(Value = "page_footer")]
        #pragma warning disable CS1591
        Page_footer,
        #pragma warning restore CS1591
        [EnumMember(Value = "page_header")]
        #pragma warning disable CS1591
        Page_header,
        #pragma warning restore CS1591
        [EnumMember(Value = "paragraph")]
        #pragma warning disable CS1591
        Paragraph,
        #pragma warning restore CS1591
        [EnumMember(Value = "reference")]
        #pragma warning disable CS1591
        Reference,
        #pragma warning restore CS1591
        [EnumMember(Value = "text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
        [EnumMember(Value = "empty_value")]
        #pragma warning disable CS1591
        Empty_value,
        #pragma warning restore CS1591
    }
}
