// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    /// <summary>Type of transformers auto-model to use.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TransformersModelType
    {
        [EnumMember(Value = "automodel")]
        #pragma warning disable CS1591
        Automodel,
        #pragma warning restore CS1591
        [EnumMember(Value = "automodel-vision2seq")]
        #pragma warning disable CS1591
        AutomodelVision2seq,
        #pragma warning restore CS1591
        [EnumMember(Value = "automodel-causallm")]
        #pragma warning disable CS1591
        AutomodelCausallm,
        #pragma warning restore CS1591
        [EnumMember(Value = "automodel-imagetexttotext")]
        #pragma warning disable CS1591
        AutomodelImagetexttotext,
        #pragma warning restore CS1591
    }
}
