// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DoclingServe.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum VlmModelType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "smoldocling")]
        #pragma warning disable CS1591
        Smoldocling,
        #pragma warning restore CS1591
        [EnumMember(Value = "smoldocling_vllm")]
        #pragma warning disable CS1591
        Smoldocling_vllm,
        #pragma warning restore CS1591
        [EnumMember(Value = "granite_vision")]
        #pragma warning disable CS1591
        Granite_vision,
        #pragma warning restore CS1591
        [EnumMember(Value = "granite_vision_vllm")]
        #pragma warning disable CS1591
        Granite_vision_vllm,
        #pragma warning restore CS1591
        [EnumMember(Value = "granite_vision_ollama")]
        #pragma warning disable CS1591
        Granite_vision_ollama,
        #pragma warning restore CS1591
        [EnumMember(Value = "got_ocr_2")]
        #pragma warning disable CS1591
        Got_ocr_2,
        #pragma warning restore CS1591
        [EnumMember(Value = "granite_docling")]
        #pragma warning disable CS1591
        Granite_docling,
        #pragma warning restore CS1591
        [EnumMember(Value = "granite_docling_vllm")]
        #pragma warning disable CS1591
        Granite_docling_vllm,
        #pragma warning restore CS1591
    }
}
