// <auto-generated/>
#pragma warning disable CS0618
using DoclingServe.V1.Chunk.Hierarchical.FileNamespace;
using DoclingServe.V1.Chunk.Hierarchical.Source;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DoclingServe.V1.Chunk.Hierarchical
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\chunk\hierarchical
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HierarchicalRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The file property</summary>
        public global::DoclingServe.V1.Chunk.Hierarchical.FileNamespace.FileRequestBuilder File
        {
            get => new global::DoclingServe.V1.Chunk.Hierarchical.FileNamespace.FileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The source property</summary>
        public global::DoclingServe.V1.Chunk.Hierarchical.Source.SourceRequestBuilder Source
        {
            get => new global::DoclingServe.V1.Chunk.Hierarchical.Source.SourceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.V1.Chunk.Hierarchical.HierarchicalRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HierarchicalRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/chunk/hierarchical", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.V1.Chunk.Hierarchical.HierarchicalRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HierarchicalRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/chunk/hierarchical", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
