// <auto-generated/>
#pragma warning disable CS0618
using DoclingServe.V1.Status.Poll.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DoclingServe.V1.Status.Poll
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\status\poll
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PollRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the DoclingServe.v1.status.poll.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::DoclingServe.V1.Status.Poll.Item.WithTask_ItemRequestBuilder"/></returns>
        public global::DoclingServe.V1.Status.Poll.Item.WithTask_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("task_id", position);
                return new global::DoclingServe.V1.Status.Poll.Item.WithTask_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.V1.Status.Poll.PollRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PollRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/status/poll", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DoclingServe.V1.Status.Poll.PollRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PollRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/status/poll", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
